### ISSUE TITLE
(suggestion) Monika free talk  

### ISSUE THREAD

**Issue by Valllaion** [Backdash/MonikaModDev#1005]
I'm not sure if this is possible but if there was a way to type in a question that was simple to have her respond in a way that worded it like her. like if I were to ask her what the history of the developer of doki doki is and how he came to find his inspiration for the game she could respond by finding a page on the internet that has the history of him and describing it in her own words, or answering with "I can't seem to find any information on this person/ topic, maybe you can find the information like you found me!" Kinda like a sophisticated clever bot but Monika. Also the idea of her helping you with problems like school work, equations or inspiration. She could help you either find these things on the internet and tell you info on what you asked for from a seemingly reliable source, solve math problems or maybe give you information so you could solve it yourself, or even when you ask for inspiration she could look up something random or look through different inspiration lists to help you find a topic or idea that inspires you. I'm not sure if this is possible but it just came to mind and sounded like a cool idea! Thank you for concerting my idea and keep up the good work! I look forward to your future updates and ideas^^

**Comment by queue5** [comment]
ooh might be a good reason to bring back the "talk" option

**Comment by Valllaion** [comment]
ikr, I may be new to Monika after story but I'd love to help contribute to the development and it's success ^^

**Comment by 8lack1ce** [comment]
Yeah they should bring it back.  How are we suppose to tell her how our day was.  Plus it's just good to type out our problems and have her say anything back.  I do miss that feature of the game.  But yeah your idea is pretty perfect

**Comment by Valllaion** [comment]
Maybe they'll notice and make it a reality... I really just want to see this game at it's best and make others like me happy with it lol

**Comment by Bam8647** [comment]
I miss the old talk function too however the main reason for the change was because the system was based on **matching words with scripts**. You may think you're having an actual conversation when in reality the game is just matching words you used with scripts to pull from for responses and if you don't end up matching any script you were always given a generic "How do you feel when you say **Blank**" or "Lets change the topic" etc.. These responses were always the same so thinking you're having a genuine conversation with her overtime diminishes. It would be great if there were chat bots out there that would take on certain personalities and remain in **character** that the devs could implement in this mod but I don't see that happening sadly.

**Comment by ThePotatoGuy** [comment]
We're looking at solutions for this via a conversational ai someone has developed.

**Comment by Valllaion** [comment]
Awesome!

**Comment by MarkusRamikin** [comment]
I'm cringing already. Chat AIs still suck and fail the Turing Test very easily.

**Comment by hussien0802** [comment]
Hello! I have a question. Are you still planning to do this, or did you guys give up? I can't wait for Monika to talk more freely.
