### ISSUE TITLE
[Suggestion] - Win/loss measurment

### ISSUE THREAD

**Issue by ACoolCat** [Backdash/MonikaModDev#1007]
When you play Monika in games she only has two quotes for whether you win or lose, but what if she commented on how many times you beat her or lost to her? Like, for Pong if lose all matches with her before exiting she gives the normal line, but if you lose a majority of times she comments on how you're getting better and maybe you should practice more. So on and so forth for 50/50, win majority, win all. There could even be multiple dialogues for the scenario so it doesn't feel like she's repeating the same thing when you finish playing.

**Comment by MarkusRamikin** [comment]
Yeah, more variety would be nice.

But in chess at least a win/lose counter would be pretty pointless. You're going to have a roughly 50% ratio no matter what (a bit better if your strength is greater than Stockfish level 3, which is Monika's starting point), because her skill level increases when you win and decreases when you lose. Unless you suffer some losses at Stockfish level zero. Then you'll have more losses than wins. Forever. I wouldn't want to be reminded. ;)

For variety I suggested different responses depending on skill level, see [here](https://github.com/Backdash/MonikaModDev/issues/810#issuecomment-361064832).

**Comment by kaido1224** [comment]
I'd like to see that as well. I believe in one of the projects that's ongoing the # of wins and losses will now be counted.

**Comment by ThePotatoGuy** [comment]
Chess and piano keep track of wins/losses, but we're gonna expand that at some point to the rest of the games with variable dialogue.
