### ISSUE TITLE
Playing "Your Reality" Extra note?

### ISSUE THREAD

**Issue by TexvinArt** [Backdash/MonikaModDev#1033]
Hello, I've been a fan of the mod for over a month now and recently have tried playing along with the song for "Your Reality" in the Piano. It's great so far, however in the part where she says "In my hand, is a pen that will write a poem of me and you", I believe there is an extra note. I recorded what the notes are according to the default setting (and Monika's Happiness level) and is currently... oopouioiuyewqewut ... However, I believe that the q is not supposed to be there. Whenever I don't type the q note, Monika makes me restart. It goes currently in detail (at least to the best of my knowledge)...

o - In | o - My | p - Hand | o - Is | u - A | i - Pen | o - That | i - Will | u - Write | y - A | e - Po- | w - -Em |
q - ? | e - Of | w - Me | u - And | t - You |

I apologize if this is supposed to be like this and I simply missed something. Hope to hear soon :)

**Comment by juliathegolden** [comment]
oo p o uio iuy e w q e w u t

So I actually agonized over this yesterday. I even read the source code to try and figure out the notes and what I discovered is actually, the o in the beginning is what's extra.

think of it this way, my dude.

o - and | o - in | p - my | o - hand | u - is | i - a | o - pen | i - that | u - will | y - write | e - a- | w - -poem |
q - em | e - Of | w - Me | u - And | t - You |

I mean, I totally know how you feel, but the q is very clearly the same note as the '-em', so this is the best way to think of it imo. There are a couple little lines like this that require an extra o in the beginning.

**Comment by ThePotatoGuy** [comment]
```
in my hand is a pen that will write a po-em of me and you
o  p  o    u  i o   i    u    y     e w  q  e  w  u   t
```

**Comment by juliathegolden** [comment]
Okay, so, I really just want to know. Is it intended behavior to be able to skip the extra lines? Because Monika will allow you to skip the musical notes between phrases if you add the extra o at the beginning of the lyrical phrases. 

This is copied from the code: 

### HOW TO FULL COMBO:
# (Everday, I can imagine a future...)
# o o o oiu uio u y t y u t w
# opo opo ] ] p[ op [ o
# (In my hands, is a pen...)
# o p o uio iuy e w q e w u t
# opo opo ] ] p[ op [ o

# (The ink flows down...)
# o o o i u t t y u o

But This simpler version, with extra notes, also passes:

### HOW TO FULL COMBO:
# (Everday, I can imagine a future...)
# o o o oiu uio u y t y u t w
# (In my hands, is a pen...)
# oo p o uio iuy e w q e w u t
# (The ink flows down...)
# o o o o i u t t y u o

This is also true for the second verse.

**Comment by ThePotatoGuy** [comment]
Yes.

**Comment by TexvinArt** [comment]
Thank you very much for the help :)
