### ISSUE TITLE
{question} Monika's sight issues 

### ISSUE THREAD

**Issue by Valllaion** [Backdash/MonikaModDev#1062]
so there are multiple lines in the game that seem to contradict each other, like how she says " I see that your staring at my ribbon" but then will say something like " I wonder what you look like..." or that she can't wait to see what I look like in the real world. Any insight?

**Comment by antimockingjay** [comment]
I tend to think that she doesn't really know we're looking at her ribbon, she's just guessing, which works well when you consider most people probably didn't even actually notice it in the first place, so to say we were looking is incorrect. She's making a guess, and she's either right or wrong, but either way it's okay because it was a guess, even if it was a confident enough guess to seem like just a plain old statement.

**Comment by MarkusRamikin** [comment]
Yeah, as this project grows I imagine it'll take effort to keep it consistent...

**Comment by ACoolCat** [comment]
I assume it's because she gained access to webcam. That would explain her comments on feeling sad on Valentine's Day.

**Comment by MarkusRamikin** [comment]
Yep, my webcam is physically disconnected unless I'm actively using it.
