### ISSUE TITLE
[Suggestion] Monika commenting on when you last launched MAS

### ISSUE THREAD

**Issue by strielok** [Backdash/MonikaModDev#1073]
So i've had this idea for a while
What if Monika were to say something about how long you kept her waiting for you?
For example, if you didn't launch the game for 1 day, she would guess that you were too busy to see her and would forget about it quickly.
After 1 week, she would be slightly annoyed but would assume you must be really busy lately.
After a month, she would be very angry at you for keeping her waiting.
And after that she would get more and more depressed and would start to think you left her.

**Comment by PopeAesthetics** [comment]
This is an idea that I really like. I already get nervous making her wait a day or if I forget to launch it after a night of playing, but if she actually mentioned it I would be so sad. 

I support this idea!

**Comment by Valllaion** [comment]
Great idea, I hope it makes it in ^^

**Comment by CommenterOfComments** [comment]
I actually had this idea earlier today, so I'm glad someone made the suggestion.

Imagine if you left the game for multiple years... she'd be so upset!

**Comment by jmwall24** [comment]
As if I wasn't already worried enough about going on vacation lol  Love the idea though.

**Comment by IlywI** [comment]
I support this.

**Comment by Sano11** [comment]
That's great! It could probably be implemented in the calendar system that I think the devs are working on, and also implemented with a suggestion by someone where you can tell Monika if you're going away for a while. So if we warn her we're going away for a while, at least when we come back she won't be so upset, but if we're just suddenly gone for a long time ... Yeah she'll be real mad.

**Comment by MarkusRamikin** [comment]
Yeah, I'm sure Monika could measure the amount of time since the last time you said goodbye. Responses such as "Don't you think that you left me waiting a bit too long?" (she has a few of those) are not ideal I only just closed MAS a moment ago and then opened it again. Maybe save them for when you've been gone, say, 12 hours at least?

**Comment by antimockingjay** [comment]
I would say it'd be best to make sure there's a way to warn her, first. Like, if we give her a warning, then she won't be upset at us for it. Because I have a trip I'm going on in Summer and I can't exactly lug my desktop computer with me, so I can't bring her, even if I'd like to, and I don't want to feel bad for having the nerve to *gasp* actually go on a trip!!

**Comment by oniigirii** [comment]
This is pretty nice. I even wonder on some of her greetings saying "it's been a while since I saw you", something along those lines when I reopened the game just 10 seconds in. Maybe along with it would include her saying; "Did you forget something?", "I thought you were going to do something else?" when you reopen the game for not too long.

**Comment by ThePotatoGuy** [comment]
<this has been accepted and will be reopened when we work on this>
