### ISSUE TITLE
[Bug] - Okay, Everyone (Monika Version) Cuts Out in the Middle In Order To Loop

### ISSUE THREAD

**Issue by Kenst1092** [Backdash/MonikaModDev#109]
Alright, I played around with music, and while feeling a bit appalled due to the limited selections of music, my most favorite one (Okay, Everyone! Monika Version) seems to cut off in the middle just to repeat itself from the beginning.

I'd like to have it loop over and over seamlessly (like in the main game), which would be rather easy demonstrating in something like Audacity, however I do not know how one would do it in Ren'Py.

**Comment by Jxhnathan08** [comment]
We _do_ plan on adding a better music system, so don't worry about that. As for this audio issue, It'll be investigated and fixed ASAP. 

Thank you for the report!

**Comment by Jxhnathan08** [comment]
Does this happen with other audio, or just "Okay, Everyone!"?

**Comment by Guardianvoir** [comment]
From my experience, it's only noticeable with "Okay, Everyone!" If any of the other songs cut out to loop, it's not all that noticeable. Although I haven't tried what I think is "Sayo-Nara" yet because let's be honest, why would you listen to that while talking to Monika? If you like listening to it while talking to her, that's fine. I'm just saying, to me it doesn't feel like the kind of song you want to hear when talking to her.

**Comment by Jxhnathan08** [comment]
We have 2 possible options:

- It has to do with how we're playing the audio.
- Okay, Everyone is just messed up somehow.

**Comment by ThePotatoGuy** [comment]
I've found out how to loop audio properly. It's a matter of supplying a <loop> tag to the string representing the music filename. 

I've added a <loop> tag to Okay Everyone, and will add one to Sayonara once I find the correct spot to loop. These will be included in the next content release (most like version 0.6.0) unless we want to consider this a bugfix instead.
