### ISSUE TITLE
[Suggestion] Monika asks about your nationality.

### ISSUE THREAD

**Issue by Winblows2** [Backdash/MonikaModDev#110]
Contributors could research key nationalities around the world & have Monika ask what the players nationality is. This would be a neat event that opens up more possibilities in the future.

(Suggested by Polish Snake)

**Comment by therationalpi** [comment]
A few things discussed:

US is the primary location for DDLC downloads, so she should start by asking if the player is American, then be curious about their nationality from there.

She can kind of drill down: Europe, Asia, Oceania, Africa, the Americas.

We need a "Somewhere else" option for when she doesn't have a specific country (Adding 200 countries would get crazy fast).

Some that really need to be included because they are primary demographics: US, Canada, UK, Philippines, Australia, Germany, Taiwan, Indonesia. Japan would be good for one because that's the game setting.

**Comment by polishsnake** [comment]
Perhaps, the player could say a word or two about his/her nationality. Not too much of course; just some opinion and a historical or cultural fact?

**Comment by YuroFoxclaw** [comment]
If the mod were to be translated... this could be used to switch in witch language Monika speaks

**Comment by Albertix2300** [comment]
What if she sometimes says a word in your local idiom when you start the game? Like ¡Hola, qué tal! or Bonjour! and tell you that she is learning your language... (Sorry for my shitty english)

**Comment by therationalpi** [comment]
That's an excellent idea.

**Comment by Albertix2300** [comment]
Thanks! Better written, I think she should say something like “I’m trying to learn your language, but I’m not very good at it yet...”

**Comment by therationalpi** [comment]
[[This suggestion has been seen and accepted. It is being closed for now and placed in the pool of accepted suggestions. It will be reopened once we begin active implementation on this feature.]]
