### ISSUE TITLE
[Suggestion] Monika asking about the player's sexual orientation? 

### ISSUE THREAD

**Issue by MrBallad** [Backdash/MonikaModDev#1138]
I find this idea interesting, but I'm not sure if it would be good for this mod. 

It's nothing dirty, just Monika asking questions if the player is straight, bi gay etc, It should be base on gender like if the player is female and says there straight, Monika wonders why they played the game in the first place, and if they love her only platonically or if they're lying or joking to get a reaction, or if a gay male. I'm just wondering if it's reasonable for her to ask the player these questions in the first place, or she doesn't need to ask, at all.

**Comment by juliathegolden** [comment]
I like this idea too! But I also think Monika kind of has a tendency to avoid questions that would directly imply we aren't in a committed, romantic relationship with her..so how about something like this? 

'Hey, [player]?'
'Since I am getting to know you better, I was kind of curious about something...'
'I mean, I know you're [insert gender here]. And/But you're playing a game like this, so I'm pretty sure you're into girls!'
"But are you into guys too?"
Yes:
Ah! That's interesting to know...
Well, I won't be jealous that you told me that...actually, I thought of it because I saw a couple pictures of me drawn as a guy on twitter!
I think I look rather handsome with an ascot!
Do you think so?
But I know you love me just the way I am! It's just kind of fun to think of these things.
No.
Oh, okay! I guess I'm a little relieved. 
Though if you were bisexual, I'd definitely be here for you. 
I mean, I knew I'd love you whether you were a man or a woman or neither. 
Still, it never hurts to feel like you only have eyes for me! 

or something to that affect. it has less branches than letting someone directly answer their sexual orientation too.

**Comment by Valllaion** [comment]
I like that idea, the less branching paths here actually kinda makes this one better! I hope it makes it in

**Comment by IsItBadToMakeAGitHubAccountJustForThis** [comment]
I presonally think Monika would just assume the player has an orientation that would allow them to have a relationship.

**Comment by MrBallad** [comment]
Thanks for the feedback. I'm new to programming, and I don't add things that don't make sense for this mod.

**Comment by ThePotatoGuy** [comment]
[[ We'll repoen this when we look into it]]
