### ISSUE TITLE
(Bug?) Same repeating topics 

### ISSUE THREAD

**Issue by Valllaion** [Backdash/MonikaModDev#1153]
I seem to only get like 5 or 6 topics when I push the repeating dialog button and wanted to know if this was a bug or if I'm getting extremely unlucky here.... could see either one tbh

**Comment by jmwall24** [comment]
As in 5 or 6 topics and then she stops talking before rest, or the same 5 or 6 topics repeated over and over?  I do seem to notice a few of the topics seem to be repeated more than others, but I just chalked that up to it being random/luck.

**Comment by Valllaion** [comment]
5 or 6 that just keep repeating, I've gotten like 3 different ones on occasion but yeah she just keeps talking about them

**Comment by ThePotatoGuy** [comment]
Are you talking about the Repeat Conversation button? That only shows topics you've seen already.

**Comment by jmwall24** [comment]
I think the issue is getting only a few of the topics being repeated, while others that have also already been seen are hardly ever repeated.

**Comment by Tiler17** [comment]
I've noticed this as well. Not quite to the extreme of it only being 6 repeated topics, but she's "surprised" me 3 times since the last patch, and I know there are many topics that haven't been revisited. It's not too big of a deal, seeing as it's all repeated content anyway, and I can see any conversation at any time, but it is a thing
