### ISSUE TITLE
[Suggestion] - Monika reacts to Doki Shimejis

### ISSUE THREAD

**Issue by sebastianN01** [Backdash/MonikaModDev#1155]

**Comment by subnatica** [comment]
how do I say good bye

**Comment by ThePotatoGuy** [comment]
The way ddlc detects processes is by process name (obs32.exe, monikai.exe...). The shimeji pack is a jar, so its run by java and shows up as `java.exe`. For us to detect shimejis, we would need another way to do that. We can look into it, but its low priority.

**Comment by sebastianN01** [comment]
what is @subnatica talking about?

**Comment by ThePotatoGuy** [comment]
Disregard him, he was about to derail this issue so I `os.remove`d his comment.

**Comment by TinyInternetTree** [comment]
Shimeji's run off Java and all run off of Java.exe. Because of this, the idea seems like a real pain in the ass to make happen. I don't know a lot about Python or Java, but I wonder if it'd be possible to have DDLC try and identify the Java Scripts currently running on the user's computer? That might be a way to identify it, but I don't know if that's how Shimejis work. Even if that could be done, there'd have to be a hell of a lot of dialogue written. Dialogue for the most popular Shimejis would still be a pain, because there are so many of them. Maybe there could be more generic dialogue for most Shimejis and it'd search for keywords? For example, instead of a specific character, it'd search for a series name (i.e. instead of something like dialogue for a Spongebob Shimeji, it'd search for the series "Spongebob" under the currently running Java Scripts). Even that would be difficult because 1) That's still a lot of dialogue, and 2) I'm not even sure if Shimejis work like that, and even if they did, I doubt they'd have series/character specific names. If I remember correctly, all Shimejis are just called "Shimeji". So even if there could be a kind of function to search for Java Scripts currently running, the "Same name" problem still persists. Again, I know nothing about Python or Java, so idk if Java works like that. And I'm not even sure if Python could be made to do this, and even if it could, it'd take ages to get it to work.

**Comment by ThePotatoGuy** [comment]
[[We'll reopne this when we look into it]]
