### ISSUE TITLE
 Interaction with the cursor ? and more.

### ISSUE THREAD

**Issue by Hooddies** [Backdash/MonikaModDev#132]
(i don't know if i should put this in " pull request ")

i just found this gif and i'm curious if this is difficult to do  ? 

http://i0.kym-cdn.com/photos/images/newsfeed/001/305/140/284.gif

i also remember a gif, where the player  give some pat on monika head or just touch her cheeks make her blush. ( i can't found the link again... )

maybe the cursor can be the hands of the MC ? ( we don't see the hand, of course. )

 but i'm not sure if this fit the game... some mobile games already do that.

also when i think about it... 

does any of you have play the game " Sonicomi " i found the mechanic for the date/conversation really interesting maybe you can use it with monica ? that can make her more... alive.

  https://www.youtube.com/watch?v=-9vDNQGWNzg&t=344s

 when you have to make a choice  she continue speaking... this not much but... why not ?

and i think i found one mispelling :
![against](https://user-images.githubusercontent.com/33403021/32674803-f1c0b7aa-c654-11e7-81b9-6e159f2965ba.png)

**Comment by therationalpi** [comment]
Typo is getting fixed in the next release.

As for the animation. I've actually had a chance to chat with the guy who made that (and the blushing animation) a while back. It was built using a Live2D, which is a framework for making 2D images into "fake 3D" rigs for animation. And while it *looks* like he's doing that in the engine for DDLC, he's actually faking the engine, because Live2D is completely incompatible with Renpy. I know I was disappointed when I found this out, but it pretty much means that we can't include any of those sorts of animations in our mod.

We do plan to include more art for Monika in the future, though! They'll be static poses and expressions, like there were in the other acts of DDLC, and we'll be rolling them out as soon as our artists have finished them!
