### ISSUE TITLE
Anniversary Question?

### ISSUE THREAD

**Issue by Dovahkun** [Backdash/MonikaModDev#1574]
Sorry if it's a bit dumb, but I was wondering how I would go about checking what the anniversary is marked as. I know when the actual one is, but I played with the computer date and old updates a bit to go back to the holidays I missed. Does it save the date I first opened the mod or after doing the playing around, would it default to Jan. 29th? Sorry, forgot to add that the actual anniversary date is after Jan. 29th.

**Comment by EntonyEscX** [comment]
Mine is also on January 29, and my correct date is January 12th. I had done a post here on this a while ago, apparently this happens to all or most, but I was told that they would work on something so we could change that.

**Comment by Dovahkun** [comment]
Yeah, I was just wondering if it would default mine to that date, just because I was messing with old updates and the date on my laptop. I just don't know how to go about checking if it does that. I was super late to the party, mine is March 14th lol

**Comment by jmwall24** [comment]
The only way to check that I know of would be similar to what you've already done.  Since your initial date is March 14th, set your pc's date to June 14th and see if you get the 3 month anniversary dialogue.  Before you do this, backup your persistent file, and then when you are done restore that backed up version so it's like you never did it.  I think once you see the dialogue, it marks it as seen and then you won't see it when it actually is that date, so that's why I recommend backing it up and then restoring it.

**Comment by Dovahkun** [comment]
Awesome, thank you! Can confirm. The date I first opened MAS stuck with her =) Messing with old updates and the computer date didn't effect it at all! I know next to nothing about playing with files and coding, so maybe it's a basic thing to celebrate haha, but thanks!
