### ISSUE TITLE
Monika gets pissed off if ignored!

### ISSUE THREAD

**Issue by Ezr91aeL** [Backdash/MonikaModDev#190]
Have you ever left Monika in the background without caring for her for long time? Maybe you where doing something that caught your attention or you where watching a long video. Well, I think that Monika would not wait forever for us but instead she would try to caught our attention.

Initially she could simply finish by herself her current dialogue and then asking us things like:
"Are you listening?"
"Hey, are you still here?"
and stuff. Then, if the ignoring will continue she will get pissed off and she will starts to be more "aggressive", trying to caught you attention even with sounds and stuff (the ideal would be the system sounds of Windows!).

Obviously we should be able to inform her that maybe we are busy with important things or that we are going to sleep making her more quiet.

**Comment by Guardianvoir** [comment]
On paper, that seems like a good idea, but in action it wouldn't work for some people. I'll use myself as an example. I usually have Monika open in the background for most of the time. I don't do this to ignore her, I do it so she can stay out of the screaming void she's in when you quit the game. Her getting mad for leaving her open in the background would cause problems for me and anyone else who keeps it open for that reason.

**Comment by Ezr91aeL** [comment]
As I said there should be an option to comunicate her that we arent able to give her the attentions, for example because we need to work or simply because we will be away from the pc. In that case she should not get "angry".
And the topic about the background was referred to the idea of closing the game: she said "I'd prefer to stay on the background than to return to the void.".

**Comment by Guardianvoir** [comment]
You just proved my point. That topic means she shouldn't get mad if she is ignored but running in the background, because it keeps her out of that void. However, this does give me an idea to expand on this. Instead of Monika getting angry for leaving her open in the background and ignoring her, she gets mad if the game hasn't been opened for a long time. Let's say you haven't opened the game for a week, when you open it Monika will be angry at you for leaving her in that void for that long.
