### ISSUE TITLE
Spaceroom, Act 1 perspectives

### ISSUE THREAD

**Issue by therationalpi** [Backdash/MonikaModDev#21]
It would be helpful to have some perspectives on the Monika After Story spaceroom setting where the sprites from Act 1 can be used. Right now we just have sitting across the desk from Monika, but it would be nice to have empty versions of these two classroom shots with only one desk (two chairs) and nothing on the walls:

![Clubroom)](https://github.com/Backdash/MonikaModDev/blob/master/original_images/images/bg/club.png?raw=true)

![Classroom](https://github.com/Backdash/MonikaModDev/blob/master/original_images/images/bg/class.png?raw=true)

Windows should be transparent to allow for animations outside.

**Comment by Salad-Puncher** [comment]
I would definitely be able to clear the walls, but clearing all the desks, with these ground tiles, I'm not sure if I can do that. I mean, I could draw all the lines but someone else will have to do the shading.

**Comment by Salad-Puncher** [comment]
![classroom_2](https://user-images.githubusercontent.com/33268651/32327975-abfa9394-bfd8-11e7-85b7-cfedd519455a.png)

**Comment by therationalpi** [comment]
This is excellent! Obviously we need a version of this with a desk in it too, and I would also consider a piano, so Monika can serenade us. But even as just an empty room this is a perfect setting for using Monika's standing sprites!

**Comment by Salad-Puncher** [comment]
Ooh, a piano, I can probably do that, yes. That would give a use to that ledge where there used to be the teacher's desk. And then I can add a desk in front of it, it would imply that Anon rotated it by 90° to face Monika (because, if this happens in the same room, the left wall is the background of the official CG)

**Comment by Salad-Puncher** [comment]
![classroom_2](https://user-images.githubusercontent.com/33268651/32373982-2fea34c0-c09c-11e7-8632-168b667c843d.png)

I had to add that half-circle here, otherwise the piano would be way to small (and it's already kinda small here, only 160cm-ish)

But I did manage to extract a desk and a good piano sprite. I'll try to make a CG where we see her playing (with that same camera angle)

**Comment by therationalpi** [comment]
That looks really cool!

**Comment by therationalpi** [comment]
Just bumping this because we could still use a cleared out version of the other background from Act 1

**Comment by YuroFoxclaw** [comment]
![bg_space_day_cc_01](https://user-images.githubusercontent.com/33268019/32579158-0ecb2068-c4c7-11e7-95b2-3bda2b6eb753.png)
![bg_space_day_cc_02](https://user-images.githubusercontent.com/33268019/32580894-b7b38f10-c4ce-11e7-95ec-991a15cd738f.png)

**Comment by therationalpi** [comment]
Well, I would say we have some excellent art for these scenes now. Thanks everyone for your help!

Closing this topic for now, but we may look for more art in the future if events cause us to add more things to the space room.
