### ISSUE TITLE
[Suggestion] Make Monika's chat triggers more specific 

### ISSUE THREAD

**Issue by MadHaetter** [Backdash/MonikaModDev#231]
Mostly what I'm asking for is that when I use words like 'will' in a sentence Monika doesn't instantly start talking about her free will topic (e.g : "Of course I will do that, I love you too." ).

Other stuff like addressing her is annoying as she starts talking about her name (e.g. "Sure Monika.")

There are many more those were but two examples, I am happy to start doing edits to correct this myself, I just want to check if it's ok to start changing things like that before I start doing it.

A change kinda like this so as to interpret most of the ways you can ask about her name:

init 5 python:
    for key in ['monika', 'just monika', 'yourself', 'your past', 'your childhood']:
VVVVVV
init 5 python:
    for key in ['your name', 'just monika', 'about yourself', 'your past', 'your childhood','name monika']:

Thanks for considering this.

**Comment by Winblows2** [comment]
If you wish to correct these issues, it will be a welcome addition to the repository. I'll keep this marked for future reference.

**Comment by MadHaetter** [comment]
While going through I noticed some keyword overlap, where some topics shared one or two keywords. This  doesn't seem to actually crash the game as some of the overlap is in current version but should something be done about it? 
How does the overlap work, does the game ignore one topic or pick a random one or something?

**Comment by therationalpi** [comment]
There is supposed to be overlap, the feature allowing for overlapping keywords was added in version 0.3.0, I believe, and for the moment she picks a random topic that fits any of the keywords in your prompt. The main reason for this is that Monika has multiple things to say about certain topics, and it also makes assigning keywords easier for writers since you don't have to worry about the keywords of over 100 topics when picking the ones on yours.

**Comment by therationalpi** [comment]
Okay, just to be clear on this, there are two different things going on here:

Words being misinterpreted - Words like 'will' have multiple meanings, and Monika misinterprets them, so we need to be more specific with keyword pairs like 'free will.'

Keywords being vague or broad - This is *not* a problem, because we want monika to trigger on a lot of words in a sort of "word association" manner. Whenever Monika goes to a generic response, that's bad for the player.

So we want to have keywords that are both *broad* and not easily misinterpreted.

This is part of why I want to replace the keyword feature with something less open-ended.
