### ISSUE TITLE
[Suggestion] Monika asks whether or not you like puns

### ISSUE THREAD

**Issue by Guardianvoir** [Backdash/MonikaModDev#232]
One of the random topics could be Monika asking the player whether or not they like puns. This question could have three different answers. "I don't like puns" could make Monika try and not use puns all that much in her topics, "I'm indifferent" could change none of the topics, and "I like puns" could make her throw in a few more puns in some of her topics.

Edit: I just realized that this is the 100th issue and it's about puns.

**Comment by MadHaetter** [comment]
An issue with this is that it would require rewriting many of Monika's topics to allow for this as instead of one topic you would need three for many of them and maybe two for some (just adding or removing puns).
Also puns are a part of who Monika is, so removing them would make her less Monika.

If your willing to put the work into this then sure it might be interesting but I don't think there really should be an option to completely change the way a person speaks, it seems too unlike how real people work to me.

**Comment by Guardianvoir** [comment]
Then she doesn't have to change her dialogue depending on your answer. She could just ask and respond accordingly.

**Comment by therationalpi** [comment]
Possible random topic idea, but changing Monika's sense of humor based on the player's opinion is just...weird.

**Comment by Guardianvoir** [comment]
To be far, if someone you know makes a lot of puns and you don't like that, you tell them and they try to stop. That's what my thought process was.
