### ISSUE TITLE
[Problem] Chess too platform specific

### ISSUE THREAD

**Issue by therationalpi** [Backdash/MonikaModDev#235]
A few testers have noticed Chess not being available for their systems. The reason is known: their system fails the check by the function `is_platform_good_for_chess()`, but this brings up the question of *why* they're system fails.

As of right now, chess is only accessible on intel chipsets ('x86' and 'x86_64'). Is this correct, or does the stockfish library support other chipsets and compatible architectures like 'AMD'.

I'm mostly asking this for @kadava, since you implemented the chess minigame. Are all compatible systems currently covered by `is_platform_good_for_chess()`, and is there any way to allow more systems to use this minigame?

Side issue, we should probably find a way to better communicate which systems can use chess, so players don't think it's a bug when they can't access it.

**Comment by Guardianvoir** [comment]
I don't know what to do about Chess not working on certain systems, but I do have an idea on how to communicate what systems it can work on. If the player tries accessing Chess and they don't have the correct system, it would prompt Monika to tell the player that they're system won't work with that game. I worded it as "that game" because you could also use that message for any future games with the same problem.

**Comment by therationalpi** [comment]
Just did a little research into this, and I think we should consider moving away from *stockfish* (which uses binaries) to some form of native python engine. [Sunfish](https://github.com/thomasahle/sunfish) looks like an alternative, which is very very lightweight. It's not going to be as strong or flexible as stockfish, but it will be a lot lighter and more portable for our purposes.

Plus, Monika's not the president of the chess club. She doesn't need to be a goddess at chess.

**Comment by kadava** [comment]
The binaries are generic 32-bit/64-bit executables. There should be no problem with executing them on AMD chipsets. The issue stems the way I decided to query for architecture. Using `platform.architecture` is apparently not reliable, which escaped my attention when I decided to use it for the first time.

The heart of the issue is the fact that it returns an arbitrary string that corresponds to the result of `uname -m` command on a UNIX system, which can be different on two computers despite them having compatible architectures. 

I think a good solution for now will be to change the way the game queries for architecture and see if the issues on AMD chipsets stop. I'm going to implement it by checking `sys.maxsize` for now.

**Comment by therationalpi** [comment]
Looks like this is working now, although there are now some problems with the 32 binary running on 64-bit windows and the command window for stockfish being visible, but those are referenced here: https://github.com/Backdash/MonikaModDev/issues/247
