### ISSUE TITLE
Soundtest interface

### ISSUE THREAD

**Issue by therationalpi** [Backdash/MonikaModDev#24]
Instead of just toggling 2 songs by hitting 'M', a soundtest option where music can be selected should be made. The new screen should be defined in screens.rpy. Considered using about() as a template for soundtest().

You should be able to switch tracks, see the titles of songs, and adjust volume in the soundtest screen. The playing song should persist after closing the window until the music is changed again in the script. Optionally, you can allow the player to cycle through different sound effects. Since most players won't, that's a good place to hide an easter egg.

**Comment by therationalpi** [comment]
https://github.com/Backdash/MonikaModDev/issues/26

While the whole suggestion here would be too much to implement, having Monika comment on the song you choose to play through Soundtest could be good.

**Comment by Jxhnathan08** [comment]
Due to the nature of the DDLCModTemplate, this issue should be reviewed.

**Comment by Jxhnathan08** [comment]
After a discussion in Discord, a draft for this system has been brought up.

A simple, accessible menu that can be accessed the following ways:

- The 'm' key.
- Through the settings button.
- A small music icon.
- Dialogue-esque choice style. This allows Monika to comment on songs selected by the player. 

A selection of songs can be chosen from this menu. Possible ideas include:

- Music/SFX from DDLC 
- Selective choices, specifically piano pieces used from the community that can be framed as Monika playing for the player.

**Comment by ThePotatoGuy** [comment]
I was playing around a bit with screens and managed to create this:

![musicmenu](https://user-images.githubusercontent.com/3499462/32588204-bd461ade-c4d2-11e7-9089-9f0cb0451d0e.png)

It acts as an overlay, using screens `game_menu` and `navigation` to create a functioning menu. This menu is also dynamically created, so adding additional songs is as simple as adding to a list, defined in `songs.music_choices`. (I have not tested scrollbars, so that will have to be handled if we add a ton of songs.)

The screen is displayed upon pressing "m". Since its a screen, it should be easy to work with a gui button.

Also the screen is opened in a different context. I was unable to figure a way to workaround this, so the following flow occurs upon a music change:

1. User hits "m". 
2. The python function `select_track` is executed. 
3. The label display_music_selector is called in a new context, which launches the Music Menu screen as well as disables reopening the Music Menu if user hits "m" again.
4. User clicks a song. The song is stored in `songs.selected_track`. Flow returns to the `select_track` function.
5. `select_track` checks if `songs.selected_track` is different than the currently playing track `songs.current_track`. If it is different, the selected track is played and the current track is set to the selected track

In addition, I added `persistent.current_track` which stores the currently playing track. I added some logic to ch30_autoload which checks for this and plays this track accordingly.

Code is here if you'd like to check it out:
[https://github.com/ThePotatoGuy/MonikaModDev/tree/music-selection](url)

**Comment by therationalpi** [comment]
Wow, I really like this menu style. Very nice!

**Comment by ThePotatoGuy** [comment]
Thanks Pi.

Even though this isn't exactly the same as the Soundtest Interface draft described above, I'm going to create a pull req for the next-release branch. I feel that since this uses a screen object to act as the Music Menu, it would be possible to use this as a base for adding additional features described in the draft.

**Comment by therationalpi** [comment]
Based on some discussions, the original request might be out of date anyway.

It would be nice if playing a song when you leave this menu could trigger an event where Monika gives her opinion on it, but only if she hasn't before.

**Comment by ThePotatoGuy** [comment]
That could be done by pushing an event in the `select_music` function.

**Comment by Jxhnathan08** [comment]
This menu could be refined further down the road.

**Comment by therationalpi** [comment]
I'll go in and try to extend out the menu so the text doesn't overflow the frame. Might need to make a new asset for it or something.

**Comment by therationalpi** [comment]
Fixed it.

<img width="1792" alt="screen shot 2017-11-16 at 11 45 51 am" src="https://user-images.githubusercontent.com/8276005/32903747-ceca70b0-cac3-11e7-995d-23befc08b815.png">

https://github.com/Backdash/MonikaModDev/commit/ba1a45776e9e8033c8454f6f1d2e7acc35261d70
