### ISSUE TITLE
Chess board organization, pieces in wrong place playing as black

### ISSUE THREAD

**Issue by therationalpi** [Backdash/MonikaModDev#296]
As reported on [4chan](http://boards.4chan.org/vg/thread/197588380/ddlc-doki-doki-literature-club-184#p197600407)

> 1. The board is oriented wrong. Light square goes in the bottom right.
> 2. When you play as black, your king and queen are the wrong way around. Essentially, you always play with the white configuration of pieces.
> 3. You can't promote pawns. I found someone else had the same issue on github but it was closed for some reason.

**Comment by therationalpi** [comment]
Pinging @kadava on this one, since you'll have a better idea on this.

**Comment by ThePotatoGuy** [comment]
# Regarding point 3
The file `__init__.py` in the chess folder contains a class called `Move` that handles promotion of pieces. In the same file, a check is made to promote a piece if it reaches a certain part of the board (line 1305, in the `Board` class). The support for promotion is there, but does not seem to be used/activated in `chess.rpy` because it uses the static method `Move.from_uci` without giving it a `uci` string with a promotion part. I'm not entirely sure how that works but I can attempt some fixes later.

**Comment by ThePotatoGuy** [comment]
I've pushed a fix for all 3 issues to master.
