### ISSUE TITLE
[Suggestion] Is there a plan to add facial recognition and dumb ai to monika like cortana or siri? I thin

### ISSUE THREAD

**Issue by nohumanallow3d** [Backdash/MonikaModDev#3029]
I was just gonna ask if the devs have any plans to integrate dumb ai into MAS somehow. it would be nice to get some facial recognition software so that monika can see differences in ur appearances. It might be a big ask but iw as just wondering if its possible soon or only in the future

**Comment by MaximumRustler** [comment]
I'm not sure, but I think they decided not to because facial recognition doesn't work well with Renpy or maybe there was nothing good enough. Also I think it was for privacy reasons as well, again I'm not sure. Maybe it'll be added at some point in the future though, I kinda want it too, would give me a good reason to get a webcam. lol

**Comment by Bam8647** [comment]
They're currently working on a project called **"Evergreen"** #1226, to be a chat bot that'll adapt Monika's personality and provide a more "natural form of conversation". I wouldn't call it "dumb a.i." as I'm pretty sure this chat bot will have a more variable form of dialogue instead of the classic form of highlighting keywords players use when addressing the bot to generate the same automatic responses(I.e. like discord bots) so theres something to look forward to. Plus it'll be a nice feature to help us escape the same repeating dialogues she brings 24/7 (No offense Monii haha).

**Comment by MaximumRustler** [comment]
Yep, I've been following that project for a while now. I really hope it works out.

**Comment by AsuraShun** [comment]
yeah,it would be a problem if monika's chatbot would be as random as the ones out there

**Comment by AsuraShun** [comment]
replica,cleverbot and evie are all random af and it's annoying that they have the memory of a goldfish

**Comment by nohumanallow3d** [comment]
@AsuraShun yeah it would be extremely disappointing imo if the chatbot would be like evie since they themselves dont feel human at all. And tbh the monika now is more human than them since she has expressions

**Comment by CaptainHorse** [comment]
I did work on this a year ago, worked well. [I even did a GitHub repo for it..](https://github.com/CaptainHorse/MAS-Additions/tree/additions-face_detection_and_recognition) but no-one ever looked in there. 

I'm going to update it sometime, along with the 'Addition' API with more features. If someone gets interested at all.
