### ISSUE TITLE
Question about sprites in the tool

### ISSUE THREAD

**Issue by ghost** [Backdash/MonikaModDev#3096]
(yup me again xD)Reading in the table issues something nice suggested, I found #3076 and thinking it was a very nice idea (and also approved but I don't know if you are working on) I tried to use the sprite tool to search some monika sprites with eyes closed (like 5dua, maybe with some z floating around her) but I noticed that some are red, so they are not available. So my question is: why they can't be used if they are seen in the tool?

**Comment by jmwall24** [comment]
Yes sleep mode is being worked on and will have it's own special sleeping sprites.  As for the ones that are not available, it's due to how the sprites are called by the mod.  Any sprite can be created, but they have to be added to `sprite-chart` before they are usable in the mod itself and not just in the previewer.

**Comment by multimokia** [comment]
As well, we don't have them all available by default because then we'd have to cache every sprite, which would take up a lot of memory
