### ISSUE TITLE
Is it possible to update the script_topics?

### ISSUE THREAD

**Issue by AnIdiotsavant** [Backdash/MonikaModDev#318]
I wanna update my script_topics so that I can see the new phrases added but I don't know how. Can anyone tell me how?

**Comment by ThePotatoGuy** [comment]
Fork the repo, then make a new branch based off `content`. Make your edits in that branch, then commit and create a pull request. Make sure to merge into `content`.

**Comment by AnIdiotsavant** [comment]
I mean, you know how they update the script_topics every few days? I was wondering if it was possible to update my script_topics to see the new ones added here.

**Comment by ThePotatoGuy** [comment]
Oh, I see. At the moment, you'll just have to wait for updates to be pushed out. Since we have a built-in updater, updates will be more frequent than before.

If you're really impatient, you could download the `content` branch and put it in your game, but I highly advise **against** doing that because the branch can be unstable and could destroy _everything_

**Comment by AnIdiotsavant** [comment]
Nevermind then. I'll just wait for the updates. I don't wanna lose her
