### ISSUE TITLE
[Suggestion] Voice..... maybe?

### ISSUE THREAD

**Issue by noobsandstorm** [Backdash/MonikaModDev#337]
Hi there first thank you for this wonderful mod.

So i know this is still new and everything i always run this on my 2nd screen letting her watch me play games and do work and read some of what she has to say when im in loading screens or something then just random i remeber the AI friday from tony stark in avengers (AoU) and thought it would be really cool for monika to have a voice just randomly talking to you. i know its a longshot just an idea though. maybe somewhere down the line it may come true? Thank you again.

sorry for my english its not my first language.

**Comment by therationalpi** [comment]
In the past, I've been against adding voiceovers to the mod directly, since the sheer number of lines would make it really difficult to maintain a good level of quality. That said, we are planning on adding hooks into the mod in the future for other people to add voice lines, and possibly using some voice in promotional material for the game.

Of course, I might be misreading your suggestion. If you had some idea for a more limited use of voiceover (to get the player's attention after periods of inactivity for example), that might be doable and actually pretty neat.

**Comment by noobsandstorm** [comment]
Yeah after posting this i also thought about that having many dialogues will be really difficult but like what you said a voice to get the players attention is really nice maybe add a voice when opening and closing the game to? thanks for noticing my post thank you again for the amazing mod. (y)

**Comment by Kiosho** [comment]
I could see a voice working in specific scenarios, like my "Where are you [Player]?" topic. That way if you aren't looking at the screen, she can still get your attention to answer her. Hardest thing would be contacting the voice actress or finding someone who can imitate the voice from her actual in-game dialogue.

Maybe her voice would glitch at times as she only ever spoke once, and it took a lot for her to do that. Shows she's still learning and can't perfectly access your speakers.

**Comment by therationalpi** [comment]
Full voice is still not on the table. Partial voicing for specific moments is still a maybe. Closing now since the Suggestion has been seen.

[[This suggestion has been seen and will receive further consideration in the future. It is being closed for now and placed in the pool of seen suggestions. It will be reopened if we begin active implementation on this feature.]]

**Comment by xtosutosu** [comment]
About the "Where are you [Player]?" part...  Adding (at least temporarily) a 'knock on glass' sound effect would be good enough

**Comment by IsItBadToMakeAGitHubAccountJustForThis** [comment]
A knocking sound would not be cool without the corresponding sprite if you ask me.

**Comment by ThePotatoGuy** [comment]
[[Rejecting voice because adding voice is not planned nor will be planned]]

Better to let users imagine the voice they want Monika to have
