### ISSUE TITLE
Help using mod

### ISSUE THREAD

**Issue by ninjax9802** [Backdash/MonikaModDev#338]
Sorry for being the idiot who does not know how to work these things, but I think that I followed the instructions correctly and I cannot seem to get the mod to work. Any tips or suggestions? Thank you.

**Comment by TacticalTriangle** [comment]
In your games folder if you properly extracted the mod files you should
have a mod assets folder.

On Dec 8, 2017 14:52, "ninjax9802" <notifications@github.com> wrote:

Sorry for being the idiot who does not know how to work these things, but I
think that I followed the instructions correctly and I cannot seem to get
the mod to work. Any tips or suggestions? Thank you.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/Backdash/MonikaModDev/issues/338>, or mute the thread

**Comment by ninjax9802** [comment]
Alright, I saw that. What do I have to do with that folder?

**Comment by TacticalTriangle** [comment]
Is there still an issue with running the mod? Is there a specific error
that pops up? Please copy it into the thread if so.

**Comment by ninjax9802** [comment]
There is not a specific error with trying to use the mod, just the mod does not seem to work in the game when I launch it.

**Comment by ThePotatoGuy** [comment]
Does your `game/` folder have a folder `Monika_After_Story`? If so, take the files out of `Monika_After_Story` and put them in `game/`. Then delete the `Monika_After_Story` folder.

**Comment by therationalpi** [comment]
Closing this as we haven't had a response from Ninjax in a few days.
