### ISSUE TITLE
Taking Monika out somewhere

### ISSUE THREAD

**Issue by ghost** [Backdash/MonikaModDev#3628]
I've seen that there are quite a lot of issues about taking Monika out somewhere and I also think there is some room for improvement.
Currently Monika has a static response after taking her out.
Besides that this could be randomized, I think her response should depend on the time the player took her out and possibly the activity the player did with her.
This basically means writing more dialog, using the absence-time as a conditional and maybe adding a menu to tell Monika what you were doing with her (I think she should know and how could she otherwise).
This menu can be added before or after taking her out, it might be a good idea to tell her the plans beforehand.

**Comment by Rai99** [comment]
#2662, #2776, #2966, #3124, #3430, #3378, #3520 

It'd been discussed and brought up previously for Monika to have some more dialogue variety when you take her out somewhere, and it's also been brought up to be able to tell Monika what you're going to do together or where you're taking her.

**Comment by Olliesama** [comment]
Well if it isn't Dennis the Menace back again to passively aggressively complain.

**Comment by dennisOdenbreit** [comment]
First pretty much every post i make gets the response 'has been brought up before'.
That is something that can be considered passive aggressive.
Here you can read that I myself stated it has been brought up before and it still gets this response.
For this redundancy it deserves a 'passive aggressive' answer.
That is your explanation to sentence 1.

Up next is sentence 2.
This is a remark that reflects reality without any Evaluation from my side. 
I know you guys get butthurt whenever someones slightly criticizes any of your efforts.
I did not criticize you though.
If you think this is criticism then you might be the one judging.
Sure I could blame you for being slow or whatever but at this point I don't expect anything from you guys anymore anyways.
I wasn't even thinking of you but of someone new trying to write some lines.

Last but not least sentence 3.
Obviously I know how to fix it (right?). I just don't care enough to actually do it myself. If your group would be tollerably acceptable on a consistent basis I might want to, but no, never.

There you go, maybe you can go on and try to reread other posts from me and actually understand what I said. Don't expect me to explain every single one of them though, this is a massive waste of my time and patience.

Oh yeah, and you keep bringing up that I care oh so much that MY issues get done soon.
Please, wake up.
It was NEVER about MY issues.
My issues are the place where I post my comments and that is all.
I don't see any reason to prioritise any of MY issues. Everything I do is state flaws and sometimes improvements. 
Everything that I used to want is seing the project move forward, if my issues are part of it then so be it.
With my third sentence you may be able to tell now that I'm tired of this because it is pointless. There are so many good things that have been suggested, no point in suggesting more unless the Implementation finally keeps up.
Once you have actually implemented the suggestions there will be no more duplicates, because people will actually play the app like it was suggested and won't have to spend their time to suggest the same missing things over and over again.
Cheers.

**Comment by dennisOdenbreit** [comment]
Took me 30 minutes to write that crap on a cell phone.

**Comment by Olliesama** [comment]
1, It's brought up that it's been suggested before because the GH issues need to be organised to it's not cluttered with duplicates. Bringing up that it's a duplicate further dissuades other people from posting the same thing within a short time frame assuming they check recent issues. It's not being passive-aggressive, it's being ordered. Unfortunately so few people check to see if a suggestion has been made before posting so it has to be mentioned.

2. I'm not a dev, you should know this because any sleight you have against me isn't on them. When I criticize you, it's not defending my work because it's NOT my work. It's not me being "butthurt" because I'm getting criticized. It's me seeing a spoilt brat wanting everyone to hang off his every word and acting entitled. If the devs lose their patience with you it is entirely deserved. I'm on the outside and I think you're just a complainer.

3. "Obviously I know how to fix it (right?). I just don't care enough to actually do it myself. If your group would be tollerably acceptable on a consistent basis I might want to, but no, never."
Of course you don't care to fix it yourself but you care enough to come around and whine about it. You like to complain about other peoples work without doing anything yourself and then try to justify it when people don't care what you have to say or think as them just being jerks, when in reality every single negative actions that anyone here has thrown at you has been in retaliation to your own poor attitude.

"It was NEVER about MY issues."
You threw a hissy fit when your issue wasn't addressed within a few days of being posted despite there being a catalog before it, this is an outright lie.

"I don't see any reason to prioritise any of MY issues. Everything I do is state flaws and sometimes improvements."
You have to state an improvement without it coming off as entitled and expecting someone else to do the leg work. Asking for things is fine, but then getting a shitty attitude because they're not done is ridiculous.

"Everything that I used to want is seing the project move forward, if my issues are part of it then so be it.
With my third sentence you may be able to tell now that I'm tired of this because it is pointless. There are so many good things that have been suggested, no point in suggesting more unless the Implementation finally keeps up."
And your complaining doesn't make it faster, you can go ahead and whine and over why isn't this done? Well the answer is pretty simple, it's because people like you who want things but doesn't do the work to make it happen. You drop your burden and desires onto someone else, and guess what? Lot's of people do that, the devs are extremely accommodating and yet all you do is whine "why isn't this done?" While ignoring everything that HAS been done, I'm so sorry that not absolutely every single request that's ever been made hasn't been done so YOURS can be done next. -_-
There is a lot of work, other things take higher priority than your requests and as such more time is devoted to it, as always you make it sound like things should be quick and easy to make when in reality it simply isn't. You're the kind of person that expects construction of a building to be done in a week. :/
And you know what else? I'm tired too, because you keep coming back to whine expecting it to be different.

**Comment by Jacobchu025** [comment]
@Rai99

**Comment by Rai99** [comment]
![untitled1176](https://user-images.githubusercontent.com/38822045/52241181-0594e300-28a1-11e9-8b41-fa3c5de278c5.png)

I'm sorry, but maybe your spiritual journey didn't last long enough. I'm afraid this all feels a bit familiar. Don't worry, maybe something will have moved when you chack back again.
