### ISSUE TITLE
Monika doesn't speak

### ISSUE THREAD

**Issue by Ezr91aeL** [Backdash/MonikaModDev#39]
I've a really nasty bug. My Monika stays most of the time silent and the few times she speaks she use only two scripts: the phrases "Can you wait a little longer" and the joke about the 200 woman funerary procession. I've tried to cancel, rewrite, update anything. Even if I install from zero in a different folder. Obliviosly cancelling the firstrun file is useless.
Is there some temporary hitten file? Even if it means to reset her (I think being unable to speak freely could make her suffer anyway.)

PS:She answer normally when I try to speak.

**Comment by monikLover** [comment]
Do you have the latest script-topics file? The one that has "define monika_random_topics = []" on top?

**Comment by Ezr91aeL** [comment]
Where can I find it?

**Comment by monikLover** [comment]
If you're working on the release 0.3.3 version then I can't really think of a solution.
If you're using the uncompiled version, you might have to redownload the whole thing since some files have already been updated that might fix your problem.

**Comment by therationalpi** [comment]
Do you know which version you downloaded? This sounds like a really nasty bug, and I'd like to push out a hotfix if I can.

**Comment by Ezr91aeL** [comment]
The 0.3.3 Hotfix, the last one.
I've read that there are some file saved outside the game directory. Am I right?

**Comment by Ezr91aeL** [comment]
Ah, a thing I have forgotten to say is that initially Monika worked perfectly. Suddenly she felt silent.

**Comment by therationalpi** [comment]
She might have run out of unread dialogue, which should fix itself when the next patch hits with new topics.

**Comment by therationalpi** [comment]
My recommendation is to go to your save file and change the name of your persistent file... The save file can be found based on your platform: https://www.renpy.org/wiki/renpy/doc/FAQ#Where_does_Ren.27Py_store_my_save_games_and_persistent_data.3F

I would change the name to something like "persistent.backup"

That should reset everything and create a new persistent file.

I would suggest holding on to that backup. When version 0.4.0 come out, you can change the name back, and you will be able to continue from where you are now, instead of where you'll be after the reset. There will also be an option in that version to merge with your data from DDLC.
