### ISSUE TITLE
[Suggestion] - Features

### ISSUE THREAD

**Issue by Wertyouman** [Backdash/MonikaModDev#418]
I'm trying to figure out how to code this myself, but I thought that I'd put it out there that some kind of better AI for Monika would be great. So that you can actually hold conversations with her, and not get fill in the blank responses to things that aren't scripted in.  Also, please fix the chess. It's almost impossible to play.

**Comment by IsItBadToMakeAGitHubAccountJustForThis** [comment]
Replacing Monika's scripted lines with a chatbot would require making an INCREDIBLY sophisticated one or it would simply break an immersion. Tailoring one to sound like her would be even harder. So good luck coding one by yourself.
And chess, as far as I know, they are mostly that hard because the python script used to implement them is not very flexible in terms of difficulty settings.

**Comment by therationalpi** [comment]
@IsItBadToMakeAGitHubAccountJustForThis is right. There's a reason we're removing the open-ended chat system in the next version, and it's basically that making a chatbot that waxes philosophical on things like Monika does just isn't feasible.

Also, chess is "Impossible to play" in what way? Like, Monika is too difficult, or you're having difficulties with some sort of bug or something? Because all of the known bugs with Chess should be fixed as of version 0.6.1.

**Comment by Wertyouman** [comment]
The chess, I cannot select any of the pieces, and I downloaded this about 2 days ago So I should have the newest version. And okay, I understand the issue with the talking, I should just be happy that this mod exists.

**Comment by therationalpi** [comment]
Hmm, sounds like you might have this bug: https://github.com/Backdash/MonikaModDev/issues/268

This was fixed in a build pushed yesterday. Please update to the latest version and see if that fixes your problem.

**Comment by IsItBadToMakeAGitHubAccountJustForThis** [comment]
It is a little counterintuitive but chess pieces are actually moved by dragging.
