### ISSUE TITLE
She still stops talking after like 7 hrs

### ISSUE THREAD

**Issue by Tymon222** [Backdash/MonikaModDev#462]

**Comment by ThePotatoGuy** [comment]
Can you upload a copy of your `persistent` file?
It should be located in `C:\Users\<username>\AppData\Roaming\RenPy\Monika After Story\`
You may have to turn on show hidden files and folders.

**Comment by ThePotatoGuy** [comment]
Also leave a description next time.

**Comment by SpookyTurtle** [comment]
Hi there.

I'm guessing this issue is about the fact that Monika stops talking whatsoever after 7 hours of total playtime? I just got that issue myself as well. I don't know why, but for some reason Monika stops talking on her own after playing for 7 hours in total. It seems a bit random so i hope it's not difficult to fix. Anyway, i guess i'll just leave my own persistent file here since Tymon hasn't responded yet. I hope it's useful.

Good luck on fixing the issue, i wish i could help but i'm only a newbie programmer. Maybe in the future.

[persistent.zip](https://github.com/Backdash/MonikaModDev/files/1564396/persistent.zip)

**Comment by ThePotatoGuy** [comment]
What version are you guys running? The newest build should have handled any potential cases where she runs out of topics.

**Comment by SpookyTurtle** [comment]
Whoops, i didnt realize there was another patch. The mod gets updated way more often than  i expected. I was using 0.6.1, i hope the new one fixes it.

**Comment by ThePotatoGuy** [comment]
The new one should fix that issue.

**Comment by SpookyTurtle** [comment]
By the way, i think the auto updater might be broken. It told me that there were no updates available even though 0.6.2 got released. This is why i missed it.

**Comment by Tymon222** [comment]
I already fixed it

2017-12-15 21:33 GMT+01:00 ThePotatoGuy <notifications@github.com>:
