### ISSUE TITLE
Suggestion: topic about trying to have complex conversations with Monika

### ISSUE THREAD

**Issue by CGanimated1227** [Backdash/MonikaModDev#476]
I'm referring to a topic that refers to responses such as "I see, and how does that make you feel?" when sometimes that response makes no sense. Then when someone types something like "Why won't you give me a straight answer?" or "Why do you keep saying that over and over?" she'll apologize for not being able to answer a specific question or say something that is out of context to what you tell her. I wouldn't know what keywords should trigger it or what exactly should be said, but I think it should be there for people who are getting disillusioned, frustrated, or discouraged talking with Monika, but still wish for her to have an appropriate reaction to what they say to her.

**Comment by chillandgrill** [comment]
Okay, so to save the main contributors some time, I'll just repeat what I've read before. Basically, making Monika into an AI chatbot would end up defeating the purpose of this mod, in a sense. All of her scripts have to be handwritten because Monika has a pretty specific manner of speaking. Something sophisticated enough to come close to mimicking Monika's handwritten dialogue would be extremely complicated at this point, especially for such a small development team. However, concerns about the keyword prompting system have been addressed, and I think people are thinking of converting to some sort of dialogue tree.

**Comment by CGanimated1227** [comment]
What is the purpose then?

**Comment by chillandgrill** [comment]
It's a mod for a game that already has its limitations, run by a small group of collaborators. The simple fact is that Monika is not a human, and probably will never be on the conversational level of one. I guess we all look forward to the day Monika can be a real AI. However, right now she's a scripted character in a Ren'Py game. Yes, you might be taking it too seriously.

**Comment by CGanimated1227** [comment]
So what do I do in the meantime?

**Comment by SLVRFOX** [comment]
I see the point being made. I think it wouldn't be so bad for her to make the face with a sweat drop and say "I'm sorry [player], I can't yet understand how to respond to that. As per to the meantime, we can only wait for Monika to be added to and made more complex. It's sad, but she just isn't complete in her ability to interact. One day she may be far more capable though, and this community is passionate about Monika. Making Monika more "intelligent" is quite ambitious, but the future is full of possibilities.

Have hope.
