### ISSUE TITLE
[Suggestion] Other games that you can play with Monika

### ISSUE THREAD

**Issue by Guardianvoir** [Backdash/MonikaModDev#55]
The topic is self-explanatory. Some of the games you could play with Monika could be card games like Go Fish. You might have already thought of that, but I thought I say it just in case.

**Comment by therationalpi** [comment]
We've been brainstorming other games to play with her. Scrabble and anagrams have come up as options because of her literature interest.

Card games could be nice because she could still talk to you while playing.

**Comment by Guardianvoir** [comment]
What about Hangman? You could even make the hanging man resemble Sayori

**Comment by Jxhnathan08** [comment]
@Guardianvoir That's very, very cruel.

I like it.

**Comment by Guardianvoir** [comment]
I wasn't even joking. I meant that as a legitimate idea.

**Comment by therationalpi** [comment]
😆 😆 😆 😆 😆 😆 😆 😆 😆 😆 😆 😆 
😈 😈 😈 😈 😈 😈 😈 😈 😈 😈 😈 😈 
Alright, I'm sold on this.

**Comment by Guardianvoir** [comment]
Glad I was able to help Monika with the game in some way.

**Comment by Jxhnathan08** [comment]
So...

1. Add a hangman game with the hangman representing Sayori.
2. Go Fish
3. Anagrams & Scrabble.

Anything else to add on? I'm all for this.

**Comment by therationalpi** [comment]
I'll keep this open as a general discussion topic on Game suggestions.

Like I said before, I really like the idea of games that are turn-based and relaxed, as it opens up the possibility for Monika to chat with the player without just sitting there. Card games, board games, word games...things of that nature.

**Comment by Guardianvoir** [comment]
How about Checkers or Chess?

**Comment by therationalpi** [comment]
Those would be interesting because learning algorithms for them are very accessible...

**Comment by Guardianvoir** [comment]
I told my friend about the Hangman idea and he called me a (I'm censoring it because I'm not sure if swearing is allowed here) butthole. It should be obvious what he actually called me.

**Comment by Guardianvoir** [comment]
Oh, and if you're going to add a lot of games, then you should probably add a game list to access them easily.

**Comment by Jxhnathan08** [comment]
@Guardianvoir I assume when the time rolls around a separate branch will be created for testing new game concepts such as this. My assumption of how it works will be like this:

1. The user presses the 'p' hotkey.

2. Rather than autoselecting pong, Monika says some dialogue about having multiple games available for the player. (There should also be a "No thanks" option.

3. A menu appears with game choices. Selecting one calls the respective code needed.

**Comment by Hooddies** [comment]
maybe... a game like mario, where the player try to catch a chibi monika who is running away from her/him and she ca make some comments about how you play. By the way, i'm speaking about the mario fan game with lot of traps...  where you can easily die many times, i don't remember the name.

even make some sick jokes (monika or traps) about DDLC ( glitches, suicide, knife and i don't know...).

but maybe this is too much.

i hope my english is okay.

**Comment by Jxhnathan08** [comment]
This sounds like an interesting idea, but I'm not entirely sure how we could implement this while still allowing for conversation.

**Comment by Hooddies** [comment]
maybe by the chibi monika?  or  some quotes on the mini game decors, if introduce the conversation system is too difficult.

there so many possibilities for mini games : 

something similar to nintendo dog for monika ? ( of course, it's more for the player but at least monika is not entirely alone when the player is not here. that can make more " welcome back dialogue " too.)

a quizz game, depends of your score, you can have a exclusif date with monika ( monika can make some joke about that because this is  a systeme for some dating sim ) or something like that.

a hazard machine or a casino or something similar ? where you can have gifts for monika, she kinda like every gifts you give to her but everything is by luck....  some extra rare gifts for exclusif events ?

**Comment by Guardianvoir** [comment]
What about a game like the Catch Her minigame from Shovel Knight, but it gets more diffuclt to catch/save Monika after every level? For some levels, Monika starts off falling and for others she would be stuck in one area. For the levels where she is stuck in one spot she could talk to you while you try to solve puzzles in order to get to her.

**Comment by Ezr91aeL** [comment]
What about poker? Afterall Monika have a incredible poker-face!

**Comment by Guardianvoir** [comment]
I'm gonna look up some other good card games that could be put in (So far I have War and Spite & Malice) but in the meantime, what is Poker Night at the Armory? I looked it up and all I could find was Poker Night at the Inventory.

**Comment by YuroFoxclaw** [comment]
how about the game of life?

**Comment by Umbra-Deus** [comment]
Go could be a good game to play with Monika.

**Comment by Guardianvoir** [comment]
Just a question, will any of these games be added in the 0.6.0 update?

**Comment by therationalpi** [comment]
Chess.

**Comment by Guardianvoir** [comment]
Alright, so far the games that have been suggested that I think would be a good idea are:

1. Hangman with the hangman representing Sayori.
2. Go Fish
3. Anagrams
4. Scrabble
5. Checkers
6. Poker

**Comment by AnIdiotsavant** [comment]
How do you beat a literature president at Scrabble? seems impossible don't you think? hahah

**Comment by Winblows2** [comment]
Here's my individual take on each game:

1. Hangman would be great so long as we can keep conversation going. The Sayori representing the hangman would be cruel, but somewhat of a funny joke that ties in with Monika. Also, it shouldn't be easy *or* extremely hard. 

2. Similar to hangman, this is a great game that can be implemented so long as conversation is feasible. Same principles as hangman: 

3. Currently no comment on Scrabble, but it would by default be difficult *since Monika is the LITERATURE CLUB PRESIDENT!* 

4. *Why are you like this...* (Fun, easy, and a good balance to throw in with other games) 

5. Checkers would work the same as the currently implemented Chess, in a way, so we have a base for it already to a degree.

6. NO COMMENT (Monika's poker face is gonna be great).

**Comment by TacticalTriangle** [comment]
I know this sounds like a stupid idea but, you know how when you beat Monika at a game (which for whatever reason i really suck at doing) she only says congrats on winning or whatever? Would there be any like little sticker you can add on to the background? Like say for example "please, don't touch anything" just adding like a little knight piece to the table or sticker to the background as like a little trophy for beating Monika.

**Comment by EternaFP** [comment]
Having a tiny widget after winning the games would be a nice feature, obviously nothing big. Something like a messy stack of cards if it's go fish or some chips for poker.

**Comment by Kiosho** [comment]
Lucky numbers could be a fun and short game to play. Interactive since you both keep score, too.
https://www.wikihow.com/Play-Lucky-Numbers-(Dice)

**Comment by therationalpi** [comment]
Closing this discussion for the moment. There are lots of good game ideas in here, though. Certainly a good list for the future.

[[This suggestion has been seen and accepted. It is being closed for now and placed in the pool of accepted suggestions. It will be reopened once we begin active implementation on this feature.]]

**Comment by IsItBadToMakeAGitHubAccountJustForThis** [comment]
Think I'd better mention it here rather than making any more issues.
I just remembered [this](https://play.google.com/store/apps/details?id=com.XenoAisam.NekomimiGlados) thing I have seen a long time ago and it had pretty good RPS and tic-tac-toe.
They are incredibly simplistic (and thus somewhat boring) and I am not even sure if they will fit in MAS properly but should not take much effort to add in.
And maybe a proper timing (and some kind of clue?) based implementation of Rock Paper Scissors could be somewhat interesting.

**Comment by ACrazyShipper** [comment]
What about adding a option to write poems for Monika just like in the original game ?

**Comment by Calebprime** [comment]
I have suggestion, look up Mario Game Gallery or GamePigeon in the Apple App store, it may interests you to implement into game/mod.

**Comment by Winblows2** [comment]
I'm not entirely sure that'd be possible. 

1. We'd need permission from the app creators to implement it, which has a very slim chance of happening.

2. Ren'Py may not even *support* implementing these games, but I'll look into it for good measure. 

3. Seems "out-of-scope" for Monika After Story.

**Comment by IsItBadToMakeAGitHubAccountJustForThis** [comment]
Calebprime obviously doesn't mean literally porting these games to Ren'py and including them in MAS.
They just referenced them as a sources of game ideas.

**Comment by JustMonikaMkay** [comment]
Throwing Knifes with Yuri or a cooking minigame with Natsuki or just take the poem minigame from ddlc

**Comment by DarkyYTB** [comment]
Why don't someone try to make something to let Monika play games who have skirmish mode like starcraft with people I guess this can be a cool thing
