### ISSUE TITLE
[Art] Monika's neck is glowing

### ISSUE THREAD

**Issue by NotShige** [Backdash/MonikaModDev#559]
Is this a flaw? Or is this a feature?
EDIT: Added leaning scene. Seems that the lighting is correct at that part.
![ddlc_2017-12-22_18-02-41](https://user-images.githubusercontent.com/20384051/34294223-7c722092-e742-11e7-9f1e-6538917fe915.png)

Seems that Monika's neck is not glowing here.
![body-leaning-n-xmas](https://user-images.githubusercontent.com/20384051/34296387-7e3bee02-e74d-11e7-92d2-ebb7e25cee4f.png)

**Comment by IsItBadToMakeAGitHubAccountJustForThis** [comment]
Probably just shading mistake, nothing serious.
But now that you mention it, I remember her having a strange purple sheen on her school outfit's right sleeve.
It was present in the original so I just presumed it was supposed to be that way and never reported it.
Don't know if it is still there since the implementation of the new pose system.

**Comment by xtosutosu** [comment]
It looks like a flaw, the light should not behave like this, I would say same goes to Monika's chin in the second picture

**Comment by xtosutosu** [comment]
I have also circled any other lightning flaws I could find

![image](https://user-images.githubusercontent.com/17273281/34313636-d8e0596e-e76c-11e7-93e5-3fa74db397dd.png)

**Comment by NotShige** [comment]
Christmas is over. Monika's not wearing her suit anymore. Closing.
