### ISSUE TITLE
Lack of consideration for other English speaking countries.

### ISSUE THREAD

**Issue by FavChanger** [Backdash/MonikaModDev#560]
This really isn't that much of an issue but it's something I want to point out. I live in Australia, and we spell words like "color" and "favorite" as "colour" and "favourite." So prompts don't pick up on the way I've been taught to spell certain words. 

And Monika talking about keeping warm is kind of unwise when it's summer in the southern hemisphere.

I'm just saying that I think it'd be nice to be a bit more inclusive of other cultures and countries in some way since when I find these sorts of things, it's a bit immersion breaking.

Other than that, what are some ways that I can help out with this mod?

**Comment by antimockingjay** [comment]
I do hope they give you a fix for this, but until they do, you may wanna try a few mind tricks, so to speak.
For the spelling, try not to think of it as "this chatbot doesn't recognize my spelling" but rather "Monika doesn't spell it that way, so she doesn't understand what I'm writing." For the weather, you could think of it as, "In the game, in Monika's reality, it's winter and freezing, so she's looking out for me the best way she can."
I know it's not an ideal fix, but I've found that changing perspective can help with immersion. I try not to see anything as "this is an issue with the mod" but rather "Monika is a young girl with limited coding experience, of course she's going to have a few mistakes here and there"

**Comment by Winblows2** [comment]
Firstly, I don't think this will be a serious priority for a *long* time, and here's why:

MAS is mainly based in North America. Since our writers are mostly American, it's no surprise things are generally centered around the US rather than other English speaking countries. Adapting MAS to multiple English-speaking countries, in my eyes, is unnecessary and a bit convoluted for a simple mod. 

It may be worked on down the road, but we'll stick to primarily North America/US focused topics & languages for now.
