### ISSUE TITLE
Big changes, and introduction of the Monika After Story Community Discord

### ISSUE THREAD

**Issue by therationalpi** [Backdash/MonikaModDev#568]
Wow! This really has been a wild ride so far. In only a few short months, *Doki Doki Literature Club* has exploded in popularity, and our little mod, started by a few posters on 4chan has grown to include thousands of lines of dialogue, new art, minigames, and several unique features. And while we’re still far away from the more than 1 million downloads the original game has, the mod's been downloaded more than 25,000 times and seen by many thousands more from Let’s Play videos on YouTube. It’s really heartwarming to see all this love for Monika!

## Fewer people, more progress

But all of this has led to some growing pains. With so many people playing the mod and invested in the project, it’s been getting more and more difficult to keep up with all of the topic submissions, feature suggestions, and other feedback. And our developer discord, which started off with just a handful of active modders, has swelled to include hundreds of fans of the game as well. While we love the support, keeping up a quick pace of updates and improvements has been getting harder and harder for our most devoted contributors.

With this in mind, I’m introducing a few changes to how the Monika After Story project is run. First off, we’re going to be drawing a clearer line between our core dev team and other contributors. We will still be accepting suggestions and topic contributions from anyone that would like to give them, but opening pull requests will now be limited to collaborators. We’ll be making a form for submitting new topic suggestions, and if you would like to make a more significant code contribution, we encourage you to make a personal fork with those changes and then alert a collaborator who can review the changes before opening a Pull Request.

While we understand this change makes the mod less open, it will also make it possible for our best writers and coders to focus more of their efforts on creating content, rather than curating and editing content from others.

## Same place, new feel.

The other major change is to our discord server. While this was originally intended as a place for developers to collaborate on improving the mod, the community has grown to include more and more observers and players. Rather than fighting this, we’re converting the current discord server to a Community Server, and adjusting the channels and permissions accordingly. Our goal is for this to be the best place for Monika lovers and fans of the project to hang out, share Monika content from around the web, and discuss the mod.

With this change, expect some changes to roles. Since development is being moved to a new location, roles like “Writer” and “Coder” will be removed, and we’ll be accepting applications for new moderators to help manage the conversation and minimize conflict.   Moving forward, we are also going to be more selective of recognized contributors. Previously, anyone who’s made an approved contribution to the project would be recognized as a member of the dev team. Moving forward, we will be cutting down to a core team of contributors. If you would like to be part of this group, we encourage you to apply, but know that final decisions will be based on the quality of your work and your fit with the rest of the dev team.

For those of you that have contributed in the past, however, we still want to recognize your contributions with a special "contributor" role on the fan discord with a unique color.

To make up for this change, we will be accelerating the roadmap on the addition of submods. This will allow people to make their own additions to the mod without the need to seek approval from the core dev team.  Ultimately, with all of these changes, we will be able to create an even better game going forward. I hope you are all as excited as I am with the future for this mod, and the beautiful eternity with Monika together.

**Comment by ThePotatoGuy** [comment]
I love you

**Comment by SLVRFOX** [comment]
So the dev team is moving to a separate private server...? Or is it still here but no longer publicly visible?

**Comment by Iamgoofball** [comment]
hi yes so, github stuff:

>but opening pull requests will now be limited to collaborators.

this is contrary to the point of pull requests, and the way github is designed as a site

if I'm a collaborator, it means I have merge access to branches to begin with, so why would I bother with a pull request except for by running it by the team(which can be done in house anyways)?

taking away pull requests serves no purpose other than to halt community contributions, because Average Joe might write an amazing script but can't get in touch with the dev team for Reasons, except through github, at which point he's screwed and nobody gets to see his script.

**Comment by Iamgoofball** [comment]
like, the entire point of pull requests is for collaborators to review the code before it's implemented, why make that process have to be assembled manually between random joes with no logging, accountability, or sharing with the rest of the team?

**Comment by therationalpi** [comment]
Pull requests have multiple uses, and using it as a way to send your changes to upstream repositories is only one of them. For collaborators working with others, Pull Requests are a good way to organize code reviews, get structured feedback, and offer comments.

Also, we will still be using pull requests to pull in changes from downstream repositories, the only difference is that those pull requests will be initiated by collaborators. This *does* add a step, but that step should help us to have a first filter on what changes our collaborators are reviewing.

**Comment by Winblows2** [comment]
Development *has* been moved to a separate server.

**Comment by Iamgoofball** [comment]
@Winblows2 That's understandable, but I don't see the point in locking the community from making pull requests directly.

If the only difference is going to be who presses the Make Pull Request button, why have a difference at all?

**Comment by ThePotatoGuy** [comment]
Short answer: We don't have enough people to scale with the number of pull requests we're getting. Unless you suddenly decide to devote yourself as an editor/reviewer or whatever, we're just too short staffed. Look at the Linux kernel, Linus literally just merges pull requests all day, he barely does his own dev.

In addition, a majority of our pull requests are dialogue-based, not code. We're willing to review pull requests that are code-heavy, but dialogue based ones are just proofreading exercises. We don't want our writers spending all their time curating content instead of creating it.

**Comment by ThePotatoGuy** [comment]
And in addition to that, **you** haven't made any contributions other than your first/only one, which was removed probably because it was more of an obscure reference than something that really enhanced the Monika After Story experience. 

Yeah, maybe we'll miss the average joe with the **golden** script, but at least we won't be burdened with the dozens of mediocre topics that we get every week from people like you.

**Comment by Iamgoofball** [comment]
Right, that makes sense. I'm concerned a bit more that this is going to shift the problem elsewhere, instead of solve the problem. I guess we'll see how it plays out in the long run, but I predict the issue will crop up instead with people just bugging you guys directly with a half-written script with no basic python PoC mockup for it.

Also, whoa there, I don't know if I struck a nerve or something, but I feel like you're over-reacting a little.

**Comment by Winblows2** [comment]
I apologize for what Potato said, and he didn't mean to be so harsh.

**Comment by Winblows2** [comment]
If this does cause issues, in the long run, we will be sure to correct it ASAP. It's *definitely* not a permanent thing that is forever set in stone.

I appreciate your concerns, I do. Let's just see how this plays out, yeah?

**Comment by Littlemanmike** [comment]
Just to ask, is the old style of dialogue submissions (using pull reqs) still active as y'all make the switch to the new form, or do I wait until the new system is ready?

**Comment by Waails** [comment]
MAS really brings all the happiness, not gonna lie.

**Comment by therationalpi** [comment]
@Littlemanmike For now, yes. Making a pull request for new dialogue is still open, but after this current batch we're going to be much more selective about what new dialogue we're willing to review.

**Comment by Guardianvoir** [comment]
My only question is where is the discord invite? I vaguely remember you put it somewhere else but I don't know where.

**Comment by Winblows2** [comment]
https://discord.gg/Vz9kwsf

**Comment by Guardianvoir** [comment]
Thank you! By the way my Discord username is Leon Genesis and not Guardianvoir, just thought you should know.

**Comment by Blubmanful** [comment]
Hey, quick note: Discord link in the Read Me file is expired.
