### ISSUE TITLE
[Topic] Music

### ISSUE THREAD

**Issue by JustinHerschel** [Backdash/MonikaModDev#588]
I found it a bit od that there wasn't an option for me to enter either music or piano as a topic option

Maybe she could talk about what type of music she enjoys and what songs she can currently play and which songs are easy for beginners to play.

**Comment by AUDelusional** [comment]
If people want to actually add a sort of "Monika plays songs" mechanic to the game (instead of just the Music menu) I can do the piano provided it's a actual song you can find online.

**Comment by drakesteele** [comment]
What about a search-and play function... say "play xxxxxx" to monika and have her find any match in the music folder and play it, maybe saying something like, "Ahaha! I found a song called [Title] by [Artist] - is that what you wanted to hear, [player]?  {Yes] [No] [Nevermind] - and if you say no, she just goes through matches until the player says yes to one or or hits "Nevermind" to give up. For no, you can maybe have her say, "Ok, ]player], what about [Artist]'s song [Title]?"  And if [Nevermind] is hit, then "Sorry we couldn't find anything right now, [player], but I'll listen to music with you any time! Or I can play my own song for you... I love spending any time with you, anyway, you know?"

Just ideas.

**Comment by miranimal** [comment]
Instead of having more music options, it would be cool if Monika could recommend songs. She says she liked one of Miku's songs and she also talked about Rock n Roll and rap. Maybe do a search on a specific genre from a song she would listen to? Also, drakesteele I love your idea. It would be cool if Monika could go through files that wouldn't be harmless to look through. Or, if you want to show something. there should be a folder in the mod that you can put music or pictures in there and she can comment on it? Also label the song and genre, maybe the mood of the song "moon dance soundtrack fantasy", "one of those days country sad", or label the picture like "friend", or "new york vacation", "california home", or "(players name)" so she will know what is showing? This way the key words will enable her to comment so it SOUNDS like she can actually see you or know what kind of song is playing! She should also comment with songs that she may not like it, but she will listen to it anyways because you like it.

**Comment by IsItBadToMakeAGitHubAccountJustForThis** [comment]
AFAIK Ren'py cannot retrieve a list of files in a folder much less read genres and artists of music from tags.

**Comment by Reclaimer1905** [comment]
What if the player could play his own songs while playing the game, and Monika could react to some of them. Maybe it's to hard to code (i mean, i'm like the noob of the noobs) but, it would be a nice thing to hear Monika's interact with your music and things like that
