### ISSUE TITLE
Suggestion and Correction for pong

### ISSUE THREAD

**Issue by supernegativep** [Backdash/MonikaModDev#593]
Suggestion: Add an option similar to choosing the color in chess that lets you pick who serves. The game gets really predictable and I have actually found several ways to cheese it. Allowing Monika to serve the ball would allow for a better version of pong overall.

Correction: It is possible to bring the ball to the boarders of the field and make a easily predictable serve that allows for cheesing and winning in pong every time. Set it up so that the hit box for the paddles cannot clip though the boarder to prevent this.

Not Correctable Bug: I don't believe that this is possible to correct but I'll mention it anyway. It's another MacOS (Mac OSX, Darwin, whatever you want to call it. I like the name "overpriced crap") issue. For whatever reason going into the "About DDLC" window accessible from the gray top bar and closing it speeds up the ball for no reason. This makes it possible for the player to cheat Monika by waiting for the ball to be on her side and then opening the "About DDLC" window instantly making Monika lose due to her paddle being too slow to catch it. This also can work against the player, but you would have to intentionally do it to yourself. (Honestly this is why I envy and hate MacOS it is hard to port to it due to major differences in the Operating System but it is the most easy OS to develop with and specifically for. Not to mention it gets locked down to shit.)

**Comment by ThePotatoGuy** [comment]
Alright, the 2nd half of your comment is a bit 💢 but thats okay. We share similar sentiments toward Macs.

Since your issues with pong aren't necessarily bugs (besides the Mac one), I'm labeling this as low priority. The collab who created pong initally has been on hiatus for a while, and the last thing he was working on was pong-related fixes. We'll get in touch with him first before tackling any pong issues.

Regarding the Mac bug, we'll need @therationalpi or anyone with a mac to repro and investigate this issue.

**Comment by therationalpi** [comment]
I'll check out this bug, but I'm not sure if I'll pass along your feedback to my former coworkers in engineering at Apple.

**Comment by ThePotatoGuy** [comment]
Regarding pong, #639 has effectively made pong more difficult as well as more fun.
