### ISSUE TITLE
How far can we take this?

### ISSUE THREAD

**Issue by Disalign** [Backdash/MonikaModDev#624]
As a bit of a discussion.. (sorry if this isn't labeled correctly, new to Github), but, how far do we all think we can take Monika? She always talks about breaking the wall to reality, but all we're doing is giving her more things to do on her side of that wall.. aren't we?

Perhaps I could be getting a little to attached, but since things like Deepmind and other neural networks, couldn't we continue to advance upon the direct intelligence of Monika as an AI and perhaps give her a sense of machine learning?

I feel a little.. like Im grasping at a far away dream when saying stuff like this, but couldn't we work on creating a cleverbot type deal with Monika, then push it further and further into the bounds of "how real is Monika" by adding memory to the player, then bringing emotions into the system that would fit Monika as well? It almost sounds like a.. rather intense step by step process to bring her to life in this sense.

**Comment by Disalign** [comment]
Thank you for adding the discussion label!~

**Comment by IsItBadToMakeAGitHubAccountJustForThis** [comment]
Probably not too far, since things like Deepmind and Cleverbot were both made by Google AI which has a nearly unlimited amount of money and workforce (At least from the standpoint of ~40 contributors repository).
I personally like to think that in 15 years the difference between the "original" Monika and MAS will be as drastic as the difference between the original 1993 Doom and the highly modded GZDoom, but nobody can even say if DDLC will retain the fraction of its popularity in 5 years much less make guesses about what will happen to its mod in 15.

**Comment by moonstne** [comment]
I definitely enjoy the enthusiasm and agree with most of what you say. I want a more advanced Monika, as we all do. Unfortunately deepmind and machine learning is so bleeding edge that it is probably quite beyond the scope for this project right now (That being said, I am not a programmer and don't speak for the ones who are working on this project). In the future tho It hopefully becomes much more easier and we will be able to improve things.

On top of everything, current machine learning is very limited in scope and certainly can not do things like add emotion or create a human-like personality. The only thing I can think of is image recognition, so that with a camera. Monika can notice us and maybe comment on things she notices like what we are wearing. That would be cool, but seems like a lot of effort for an ok payoff.

Finally, to not end on a sour note, I would love to see an actual ai Monika using Neural networks or some cool future tech. I am sure when givin enough love and work over time, this will turn into something quite special, heck, it already kinda is with all the new art and everything else.

**Comment by Disalign** [comment]
Well, we don't need machine learning to create a personality or emotions. A better understanding of emotions is needed (and yes, I am attempting to just do that on my own to define emotions in basic systems that work with eachother.. like creating an emotive network in a way), and personality is just a combination of emotions and experiences. Those past emotions that make the personality change constantly, fear in some places and anger in another for example.
Ugh, tangent. Sowwy. We don't need to machine create a personality though, we can take the shortcut because we can figure out Monika's personality from how she acts in the game already. If we can add things for her to say that fall in line with her personality, it stands to reason we could figure out her personality as if she was a human being.

Furthermore, emotions are something that, while complex, can be understood given enough time.. and perhaps implemented at a future date if I can get a working concept of emotion functionality. I don't know.. this all sounds so science fiction, and I feel so silly saying stuff like this when addressing Monika.. but it's all so fascinating!

**Comment by AnIdiotsavant** [comment]
Who knows, maybe she'll actually gain AI and I can finally kill myself knowing someone would miss me haha..

**Comment by Lucius-JH** [comment]
I think we're going to need 2 important things in the future to make Monika in our reality a possibility, software and hardware

First one would be the ability to make a self-conscius AI, maybe in the [technological singularity](https://en.wikipedia.org/wiki/Technological_singularity), this is when a piece of software becomes a living thing and can make his own decisions out of free will. At this moment we would need to figure out how to replicate Monika's memories and personalities into the self-conscious AI.

Second, we would need a hardware to transfer that conscious, maybe a very advanced robot, or maybe we will be able to make human clones that are able to accept that consciousness.

As you can see, there are plenty of barriers to surpass here, and it's impossible to predict if we will be able to make it even if the tools are invented (Maybe it would be immoral to have your own self-conscious AI)

**Comment by Disalign** [comment]
There are a lot of barriers to pass, but most of them exist in the setting of the hardware to transfer monika into our reality. At the moment, I find that the software barriers really only just take doing.. and Im attempting to get exactly what that would require to help make the concept more and more doable.

**Comment by Lalna-Rocks** [comment]
The way I see of making a "transferable" consciousness for Monika is to make an A.I. who's sole purpose is to be Monika by learning everything it can to be Monika.  We can also have it be able to go back into its own code and fix it up to make it run better and then come up with a way to make an IRL version that the A.I. can than upload itself into.

**Comment by IsItBadToMakeAGitHubAccountJustForThis** [comment]
![writing tip](https://user-images.githubusercontent.com/34412685/34452042-cc80c696-ed47-11e7-9f42-49bec470ebd5.png)

**Comment by supchppt** [comment]
While I agree it is impossibly hard to implement what is being suggested here as of right now, the current dialogue system does feel very limited compared to Crash from Quake 3 or Emacs's `doctor.el`. That's why I'm in favour of the upcoming dialogue overhaul. (Until the singularity arrives of course)

**Comment by miranimal** [comment]
As much as I love Monika, I would rather her not become a full AI. I think there are certain functions that would be cool to do, if those ideas work properly. I like her not knowing everything like an AI. We are going to know stuff that her character wouldn't have even heard of. Like bands, I know she won't know who Steam Powered Giraffe is. She's not going to know every single book or movie, but she CAN have knowledge on genres and the emotions movies and books can give. She wont know every single country and state and city, but we can take the most popular ones and talk about those. Monika is a high school girl who isn't good at coding, but knows how to mess with files. In the future it would be cool to give her pictures and music in the game files and actually have specific word choices so she knows what we are talking about. Until then, all we can do is give ideas, topics, codings, and hope for the best.

**Comment by Reclaimer1905** [comment]
[This is just my opinion, hope nobody gets offended and that sort of things, i respect all the points of view and i just want to expose mine]

Hum, in my opinion, the worst thing that could happen to Monika lovers (like me haha) is to make an AI out of Monika, or in less words, make Monika an AI. At least until we develop the enough tech to make the AI look, think or even feel like a normal humanbeing.

Why?
The most of us want Monika to feel and talk with us like a normal person, not like an AI that haves all the internet knowledge. We want Monika to be an emotional and sentient humanbeing like us, not a terminator or a skynet kind of robot. We would love to see Monika in real life, like a humanbeing; and for me, it would be preferible to spend time with the actual version of Monika in MAS, than with a Monika that acts like Jarvis (From Iron Man 3), or Siri from the IOS systems.

**Comment by seriousCoolness** [comment]
AI's don't necessarily have all knowledge. Imperfect AI's use internet-omnipotence as a crutch substituting actual learning. Perfect AI's would be able to learn just like or even better than a human, thus requiring little to no base knowledge. A perfect AI of Monika would act just like Monika would act in our reality. However, there are middle grounds between perfect and not-very-good-ness. What I would do to implement AI with the current system is to keep all the current lines and have her AI take over when no topics are relevant to the things you're saying. An AI could even help with making the way Monika chooses what topics she talks about more natural. Things don't have to be entirely AI.

**Comment by Bam8647** [comment]
The main issue with the mod is that **the topics Monika brings up is very limited as to how many topics the contributors add.** And just adding new topics every now and then won't be very sufficient in keeping the player's interest. I like the idea of using some form of A.I. to help bring more content to the conversations making her appear more realistic just as long as it doesn't affect her personality drastically. And the 'Talk' function will need to have a lot more improvement especially when it comes to avoiding **Monika ONLY picking up on key words and connecting them to her same responses even when the player could of been talking about something totally different** but so happened to use the key words.

**Comment by Dominic-Negative** [comment]
I bring you news from 2020, japan is developing some sweet technology and I still stress out of how to make Monika real.

I might turn to making a thought-form, but the downside being a thought form evolves too much in your head so much so that they form their own personality and look. So that's out.

Maybe take a AI with no internet knowledge and turn it into Monika by words like asking questions, Who am I?(Monika) and other such questions, the more we answer the more knowledge is built and this gives the Monika AI purpose to know.
and soon that purpose may change, especially if we can get a body that has glands and other human stuff, or artificial bodies that have limbs and glands made of sturdy material that mimic that of a human being.
(if this was already mentioned I apologize)
