### ISSUE TITLE
[Bug] - Game doesnt start

### ISSUE THREAD

**Issue by Reaper367** [Backdash/MonikaModDev#644]
When I put the files in the game and launch it it says it runs then stops nothing happens on screen other than that.

**Comment by ThePotatoGuy** [comment]
If DDLC doesnt open, then check `game/` for a folder like `Monika After Story`. If it is there, please take the files out of that folder and put them in `game/`. (The mod files **cannot** be in a subfolder in `game/`). Then delete the folder `Monika After Story`. In addition, delete the files in `game/cache/` to force the game to reload everything/

**Comment by HcaekNoiva** [comment]
I did what you said and it still isn't working.

**Comment by ThePotatoGuy** [comment]
Do you have a subfolder like `Monika After Story` in `game/`?

**Comment by HcaekNoiva** [comment]
there was one but I took the files out of the subfolder and deleted it

**Comment by HcaekNoiva** [comment]
I also deleted the game cache and still nothing

**Comment by aivyr** [comment]
> there was one but I took the files out of the subfolder and deleted it
that's the issue, because there were files in it that you would have needed to run the game! if you don't have a copy of the original `/game` somewhere, I'd say do the following:

1. get the DDLC .zip (either find or redownload it) and extract the `/game` folder into your DDLC folder
2. extract the Monika After Story folder within the `Monika After Story` zip to `/game` (don't delete anything)
3. during the extraction process you should(?) be asked whether you want to replace certain files: hit yes

**Comment by ThePotatoGuy** [comment]
1. If ddlc doesn't run when the mod is installed, then the mod files are **almost certainly** installed in a subfolder in `game/`. **The mod files cannot be in a subfolder in game.** This is the only known cause of ddlc not running when the mod is installed.
2. If ddlc runs, but it's still the stock game (the mod doesnt seem to be working), then the mod files were _probably_ installed in the `ddlc/` folder instead of `game/`. **The mod files need to be in game/.**
3. If ddlc crashes on start, look in `ddlc/` for `log.txt`, `traceback.txt`, and `errors.txt` and upload those files here (if you have them). Or take a screenshot of the error message the crash shows and upload that here.

**Comment by HeitorGTi** [comment]
Monika's screen opens
but she does not appear, only thing that appears is a chair :(

**Comment by HEAVYNAVA** [comment]
> Monika's screen opens
> but she does not appear, only thing that appears is a chair :(

... when you tell monika that you are taking her out another MONIKA file is created in the characters  folder if you don't bring that "MONIKA" file to the characters folder she'll not be there.

**Comment by Monikammmm** [comment]
I've tried everything that you all have reccomended me to do, nothing seems to work. All I get is this message:
I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/definitions.rpy", line 10, in <module>
OSError: [Errno 17] File exists: 'c:\\users\\jisha\\appdata\\local\\temp\\C-Users-jisha-Downloads-ddlc-win-DDLC-1.1.1-pc-DDLC-.lock'

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "C:\Users\jisha\Downloads\ddlc-win\DDLC-1.1.1-pc\renpy\bootstrap.py", line 295, in bootstrap
    renpy.main.main()
  File "C:\Users\jisha\Downloads\ddlc-win\DDLC-1.1.1-pc\renpy\main.py", line 364, in main
    renpy.game.script.load_script()  # sets renpy.game.script.
  File "C:\Users\jisha\Downloads\ddlc-win\DDLC-1.1.1-pc\renpy\script.py", line 265, in load_script
    self.load_appropriate_file(".rpyc", ".rpy", dir, fn, initcode)
  File "C:\Users\jisha\Downloads\ddlc-win\DDLC-1.1.1-pc\renpy\script.py", line 753, in load_appropriate_file
    self.finish_load(stmts, initcode, filename=fn + source)
  File "C:\Users\jisha\Downloads\ddlc-win\DDLC-1.1.1-pc\renpy\script.py", line 445, in finish_load
    node.early_execute()
  File "C:\Users\jisha\Downloads\ddlc-win\DDLC-1.1.1-pc\renpy\ast.py", line 865, in early_execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "C:\Users\jisha\Downloads\ddlc-win\DDLC-1.1.1-pc\renpy\python.py", line 1719, in py_exec_bytecode
    exec bytecode in globals, locals
  File "game/definitions.rpy", line 10, in <module>
  File "python-packages/singleton.py", line 45, in __init__
OSError: [Errno 17] File exists: 'c:\\users\\jisha\\appdata\\local\\temp\\C-Users-jisha-Downloads-ddlc-win-DDLC-1.1.1-pc-DDLC-.lock'

Windows-8-6.2.9200
Ren'Py 6.99.12.4.2187
