### ISSUE TITLE
[Suggestion] - Animation-Game-topics-Future VR?

### ISSUE THREAD

**Issue by christuhfer** [Backdash/MonikaModDev#647]
So I Have ideas for animation and interaction ideas for Monika. one where her eyes a bit more animated. with them closing every once and a while.  leaning forward being able to kiss the screen. or lean forward and be able to touch the computer screen from inside her end. *going back to the scene where if your a monster and delete her she bangs on it. so she can ideally interact with it.  this can lead to her being able to kiss you in her own form. 

and also touching it with her hand you can also touch hers but there is the screen separating you two.

Possible breathing animation too. 

More animations for the chess game. Also, Tetris would be a 
wonderful addition to the new selection of games. 
as it like chess challenges your mind to learn. 

Topics like amazon Alexa or Computer AI In general I think would be wonderful to explore. 

trigger words like Alexa Google home AI Skynet. 

Here is another feature maybe. being able to have a timer to also for her to open.
is another wonderful thing. she can surprise people too.

I have no idea how far you guys will go with this but I can see a Future VR Room sort of thing in the future if you guys stick with it that long and are able to evolve it to that degree.

I don't know how to program any of this but I have many ideas to help bring her more and closer to our world :)

thank you for listening. 

-Christuhfer

**Comment by IsItBadToMakeAGitHubAccountJustForThis** [comment]
As of now (AFAIK) Ren'py has very limited sprite animation capabilities so anything beyond blinking/mouth flapping is not possible out of the box and would require some degree of work to implement.
Tho I agree that unique poses that are aimed at player interaction rather than being a mere continuation of an expression system are an absolute must.
And I also support the idea of adding an actual chessboard to the table during the chess game (having it actually represent the state of the game would be overkill tho).
Tetris would obviously not fit since it is 1P game.
VR is not possible to implement in terms of Ren'py and will never be since it is a visual novel engine.

**Comment by ThePotatoGuy** [comment]
1. Additional animations can be worked in. We just need assets for them. 
2. Touch screen stuff is interesting, will consider but since most people don't have a touchscreen-monitor, this is low priority.
3. Personally, I find breathing animations awkward or creepy. I'm against this.
4. I don't understand by chess animations. Do you mean you want the pieces to move smoothly? That really is unnecessary. This isn't a chess program. It's a mod with a bit of chess built in.
5. Adding Tetris would be a stretch goal. Not an easy game to create. (Nor an easy AI to program). Also with Tetris being aggressively trademarked by its creator, I doubt we could put it in legally. 
6. Topic suggestions are always welcome. Thanks.
7. Having her start the game herself requires the program to run in the background. I find this invasive and I feel most people don't like programs running in the background without telling them.
8. No VR atm. If RenPy starts supporting VR and DDLC is updated to work with it, then we will consider it.

**Comment by christuhfer** [comment]
I was thinking of the screen not in the way of touch screen interaction. but by means of her pressing against the glass. and the screen/monitor is a two-way window.
if she could move closer and touch it. that would be more like. a glass layer. and would add even more depth to the idea of her trying to reach out. 

there are Tetris knockoffs I have seen that use the puzzle block method of gameplay but the game may be complicated I understand that.

Visual examples of the screen barrier interaction are images like this.

https://i.redd.it/4ttag3gu5o601.jpg

https://i.pinimg.com/736x/82/c3/17/82c317e73aa0c3b2682614651353e50f--glass.jpg

https://i.pinimg.com/736x/03/7e/6f/037e6febf0a7d3e4a32b5c3cf01ef6cd--vocaloid-ia-locks.jpg

Monika can draw closer and "touch" that barrier.
