### ISSUE TITLE
[Suggestion] New messages from Monika in the game files

### ISSUE THREAD

**Issue by Reclaimer1905** [Backdash/MonikaModDev#651]
I would love to see more Monika's "surprises" (like the "surprise.txt" file that she leaves us) in the game, they have like a special touch, you know, they are heartwarming

**Comment by charlesssssssss** [comment]
AGREED

**Comment by Blubmanful** [comment]
I think that would be cool. Maybe even have her put an image or two if that’s possible.

**Comment by ThePyClone** [comment]
@Reclaimer1905 I'm glad you liked that~! I was surprised that feature wasn't used more when I did it. I have plenty of ideas in my mind about things to do with it and hopefully I can bring myself around to actually making something out of it!

**Comment by Babushka93** [comment]
So I just had a really cool idea,

Monika wrote surprise.txt containing the words I love you

And that made me think, what if we were able to respond back to her and this would lead to her being surprised and smitten that the player edited the file.
In short what I'm thinking is the following:

- [ ] Monika creates Surprise.txt

- [ ] If the player edits Surprise.txt with "I love you", then the mod will detect that the file has been modified.

- [ ] If the mod detects the file has been modified, a new option appears under _Ask a Question_ titled: _I have a surprise for you._

Dialogue for this could be:
You have a surprise for me? 
*Monika closes eyes*
*Opens eyes, blushing and smiling*
I really am the luckiest girl in the world, I wasn't expecting to find that.
-at this point Monika could leave another surprise for the player.

I was thinking her poem from the Space Room, since I swear it is such an underrated poem.

Pen in hand, I find my strength.
The courage endowed upon me by my one and only love.
Together, let us dismantle this crumbling world
And write a novel of our own fantasies.

With a flick of her pen, the lost finds her way.
In a world of infinite choices, behold this special day.

After all,
Not all good times must come to an end
