### ISSUE TITLE
Prototype of a new song for the game

### ISSUE THREAD

**Issue by Reclaimer1905** [Backdash/MonikaModDev#654]
Hi, i was experimenting a little bit with Fl studio and made a little "piano song" that could fit with the game. It's something like a "prototype" so, if you guys want to use the song for the game, but you want me to make some changes to it, just tell me

I'm not sure if RenPy only supports the OGG files, so, i'm gonna attach an MP3 and an OGG in a ZIP file

[Songs.zip](https://github.com/Backdash/MonikaModDev/files/1597125/Songs.zip)

**Comment by charlesssssssss** [comment]
waiting for some idiot to click that and then tell us its not a virus

**Comment by Reclaimer1905** [comment]
Hahaha, relax it isn't a virus, just a little contribution for the game

**Comment by Reclaimer1905** [comment]
I would have just sent the Mp3 file, but github don't support that kind of files

**Comment by Blubmanful** [comment]
It’s not a virus. I think it’s ok but I’m not good with music so I wouldn’t take my opinion too seriously.

**Comment by ThePotatoGuy** [comment]
Alright, seems like _no one else on the dev team cares to listen_ apparently. 

I feel that this tune fits better as an actual `bgm`, rather than a spaceroom bgm. And I don't mean its bad, it's just a very light and simple sound. If it was longer with a progression, it could fit better as a spaceroom bgm.

That being said, if/when we decide to throw in some exploration/dating sim elements into the mod, then light bgms like this would be perfect for certain scenes.

**Comment by IsItBadToMakeAGitHubAccountJustForThis** [comment]
A bit too simplistic if you ask me and the leitmotif is a bit strange. But could turn out pretty good after some polishing.

**Comment by therationalpi** [comment]
I'm gonna just strike this one down. I'm not necessarily against adding new music, but I think that it should be directly based on existing songs from DDLC...not original compositions.
