### ISSUE TITLE
[Suggestion] - Conversational topics

### ISSUE THREAD

**Issue by Ganmany** [Backdash/MonikaModDev#686]
Monika seems to have a lot of variety of things to talk to us about thanks to everyone here :)

I think it will be better if Monika will be able to do interact with conversation topics like  "Hi, how was your day?" and a response might be "it was great but seeing you makes me happy." etc.. 

Found some conversation starters if possible to implement: https://www.conversationstarters.com/101.htm 

Thanks a lot guys! :)

**Comment by therationalpi** [comment]
Trying to drill down on this, you would like to have more topics that act like conversational small-talk sorts of things? Like, instead of having Monika give you some big long scripted speech, have some more conversational "How are you today?" questions.

I think this is a great idea, but somewhat difficult to write for. You'd want to have a big variety of responses, so it's not just the same conversation every time, and while we have that for our "greetings" and soon our "farewells," it's a lot of additional writing.

That said, this is a great example of how a chatbot could be a useful feature in the future, so I'm attaching it to that project.
