### ISSUE TITLE
[Suggestion] - 

### ISSUE THREAD

**Issue by Wolfang28** [Backdash/MonikaModDev#690]
I believe there should be some way to tell monika your gender she she can use the right pronouns including being nonbinary (using pronouns like "they" rather then him or her). It would be greatly appreciated but either way it is fine if that's too much work, this mod is by far one of the most amazing things i have ever seen come from a dedicated fan base in such a short amount of time since the games release. keep up the great work! :D

**Comment by IsItBadToMakeAGitHubAccountJustForThis** [comment]
Already implemented.

**Comment by antimockingjay** [comment]
Yeah, this is already in the game! After playing for long enough, eventually Monika will comment on how she doesn't really know your gender, and ask you what you are. The options then are male, female, and neither. I personally have it set as neither since I'm genderfluid, and they/them always applies to me, regardless of how I'm feeling. So if you haven't gotten that yet, just wait!
If you have gotten it and you selected the wrong one, you'll want to make a new post asking for help, as I'm sure someone will be able to help somehow.

**Comment by ThePotatoGuy** [comment]
#587 will take care of changing gender _on demand_. For now you need to wait for existing topic to run.
