### ISSUE TITLE
Break immersion - what to do.

### ISSUE THREAD

**Issue by gitthisissue** [Backdash/MonikaModDev#734]
So I stumble upon on this line:
https://github.com/Backdash/MonikaModDev/blob/af02c21fa957f9818e408c440aa36368d9f864b8/Monika%20After%20Story/game/script-topics.rpy#L2091

Am I the only one who feel this is breaking "immersion"?
You can just say this the 'first' time the user install the mod, but not after.

I'm a C/XUL coder. I contribute to other github using other name.
If they(player) have a love or something, they _will_ contribute without you asking.

So, can you limit this dialogue not to show in random talk?

**Comment by therationalpi** [comment]
Monika breaks the fourth wall...it's one of her defining character traits. So what breaks immersion for you might improve immersion for other people, since Monika being aware of the git repo for the mod shows her awareness of the game she's in.

Leaving this in, unless some of the writers decide it doesn't fit.
