### ISSUE TITLE
[Bug] Katawa Shoujo Easter Egg Problems

### ISSUE THREAD

**Issue by hkight** [Backdash/MonikaModDev#735]
So I've been playing Katawa Shoujo lately. I finished the Emi arc last night. I know Monika is supposed to discuss each arc as you play or finish in the game, but I'm only getting the general discussion where your save file is present. Any idea what the problem could be?

**Comment by TacticalTriangle** [comment]
maybe you didn't get the good ending and just got the neutral ending?

**Comment by therationalpi** [comment]
The functionality for checking specific routes has been removed for the moment because of severe bugs it was causing. The original code was using something of a kludge digging through the persistent file, and that was causing unexpected crashes (not sure if it was related to the version of the save file or platform issues). Regardless, that code's not active until we find a way to fix this.
