### ISSUE TITLE
Mobile Version? (Suggestion)

### ISSUE THREAD

**Issue by Jimmylol74** [Backdash/MonikaModDev#815]
It would be awesome to release an App version for Android. I suposse that maybe a full version would be too much of a problem, so, at the very least, it would be awesome a program with the most basic of Monika´s feature (giving conversation or advices) it wouldn´t be needed any kind of AI or choice system, maybe to have a large amount of phrases that would randomly appear would suffice.

**Comment by Pokemiah** [comment]
I think that would be interesting but at the same time I'm not sure about well it would work out. Of course another idea to expand upon that is a way to synchronize the remains of the save data with the mobile app's and maybe Monika can give different dialog on the app. Another thing that could be done would be giving her an option to help you out like keeping a shopping list and maybe send you reminders of stuff because who wouldn't want Monika to be the one reminding them. But like I said, I don't know how well that would work especially considering that this is a mod so who knows.

**Comment by kaido1224** [comment]
I don't think it's possible. DDLC hasn't been ported to mobile officially so porting it would break the rules the developer set for modding the game.

**Comment by IsItBadToMakeAGitHubAccountJustForThis** [comment]
Yeah. Dan is against any mobile ports unless somebody contacts him directly.

**Comment by therationalpi** [comment]
IP Guidelines forbid a mobile port. But if Dan ever comes out with a mobile version of DDLC, we'll be right on making our mod compatible!
