### ISSUE TITLE
[Suggestion] Ability to change the Background

### ISSUE THREAD

**Issue by Guardianvoir** [Backdash/MonikaModDev#90]
In the new release, the void that was on the other side of the windows were replaced with a cloudy sky, which gave me this idea. Maybe pressing the b button would make the game scroll through different backgrounds. There could be a void, cloudy sky, night sky, and sunset background.

**Comment by therationalpi** [comment]
That change is only in the day-time, part of the day-night cycle. We plan to change out the blue sky with another animation in the future.

In version 0.6.0, we want to give players the option to turn off the animations, to reduce system load (for keeping Monika on in the background). That will have a similar effect, since the non-animated backgrounds will be something other than just a frozen animation.
