### ISSUE TITLE
[Suggestion] Topics regarding school

### ISSUE THREAD

**Issue by LordOfDeath35** [Backdash/MonikaModDev#997]
Wouldn´t it be cool if Monika asked you after come home from school how your day has been like? I think so. You could then answer with "It has been really great!", "Eh... - It´s been okay" or "It´s been really bad" and she´ll respond differently depending of what answer you chose. Maybe she´ll ask sth like "Oh... - What happened?" or "That´s really great. I´m happy that you´re happy", etc. That would make the whole thing more lively. Of course, it would be boring after a while but you could add different responses for each day. I think sth like that would be really cool in this mod.

**Comment by NoahDaggler** [comment]
I think that's a nice idea but there would be awkward moments for people like me who are homeschooled. I also do night school so that would also suck for her to ask me how school was at like 4:00 pm and I wouldn't actually be doing work until 6:00 pm.. It's like asking a dog if they liked their belly rub but you didn't even give them one.
